//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.21 at 12:08:20 PM EEST 
//


package com.bulpros.integrations.regix.model.GRAO.MaritalStatusSpouseChildrenSearch;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for MaritalStatusSpouseChildrenResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MaritalStatusSpouseChildrenResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MaritalStatusCode" type="{http://egov.bg/RegiX/GRAO/BR/MaritalStatusSpouseChildrenResponse}MaritalStatusCode" minOccurs="0"/&gt;
 *         &lt;element name="MaritalStatusName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MiddleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EGN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Gender" type="{http://egov.bg/RegiX/GRAO/BR}GenderCodeType" minOccurs="0"/&gt;
 *         &lt;element name="Relatives" type="{http://egov.bg/RegiX/GRAO/BR/MaritalStatusSpouseChildrenResponse}RelativesData" minOccurs="0"/&gt;
 *         &lt;element name="ReportDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MaritalStatusSpouseChildrenResponseType", propOrder = {
    "maritalStatusCode",
    "maritalStatusName",
    "firstName",
    "middleName",
    "lastName",
    "egn",
    "gender",
    "relatives",
    "reportDate"
})
@XmlRootElement(name = "MaritalStatusSpouseChildrenResponse", namespace = "http://egov.bg/RegiX/GRAO/BR/MaritalStatusSpouseChildrenResponse")
public class MaritalStatusSpouseChildrenResponseType {

    @XmlElement(name = "MaritalStatusCode")
    protected String maritalStatusCode;
    @XmlElement(name = "MaritalStatusName")
    protected String maritalStatusName;
    @XmlElement(name = "FirstName")
    protected String firstName;
    @XmlElement(name = "MiddleName")
    protected String middleName;
    @XmlElement(name = "LastName")
    protected String lastName;
    @XmlElement(name = "EGN")
    protected String egn;
    @XmlElement(name = "Gender")
    protected Integer gender;
    @XmlElement(name = "Relatives")
    protected RelativesData relatives;
    @XmlElement(name = "ReportDate")
    protected String reportDate;

    /**
     * Gets the value of the maritalStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaritalStatusCode() {
        return maritalStatusCode;
    }

    /**
     * Sets the value of the maritalStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaritalStatusCode(String value) {
        this.maritalStatusCode = value;
    }

    /**
     * Gets the value of the maritalStatusName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaritalStatusName() {
        return maritalStatusName;
    }

    /**
     * Sets the value of the maritalStatusName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaritalStatusName(String value) {
        this.maritalStatusName = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleName(String value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the egn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEGN() {
        return egn;
    }

    /**
     * Sets the value of the egn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEGN(String value) {
        this.egn = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGender(Integer value) {
        this.gender = value;
    }

    /**
     * Gets the value of the relatives property.
     * 
     * @return
     *     possible object is
     *     {@link RelativesData }
     *     
     */
    public RelativesData getRelatives() {
        return relatives;
    }

    /**
     * Sets the value of the relatives property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelativesData }
     *     
     */
    public void setRelatives(RelativesData value) {
        this.relatives = value;
    }

    /**
     * Gets the value of the reportDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportDate() {
        return reportDate;
    }

    /**
     * Sets the value of the reportDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportDate(String value) {
        this.reportDate = value;
    }

}
