//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.21 at 12:08:20 PM EEST 
//


package com.bulpros.integrations.regix.model.GRAO.MaritalStatusSpouseChildrenSearch;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for MaritalStatusSpouseChildrenRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MaritalStatusSpouseChildrenRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EGN" type="{http://egov.bg/RegiX/GRAO/BR/MaritalStatusSpouseChildrenRequest}EGN"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MaritalStatusSpouseChildrenRequestType", namespace = "http://egov.bg/RegiX/GRAO/BR/MaritalStatusSpouseChildrenRequest", propOrder = {
    "egn"
})
@XmlRootElement(name = "MaritalStatusSpouseChildrenRequest", namespace = "http://egov.bg/RegiX/GRAO/BR/MaritalStatusSpouseChildrenRequest")
public class MaritalStatusSpouseChildrenRequestType {

    @XmlElement(name = "EGN", required = true)
    protected String egn;

    /**
     * Gets the value of the egn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEGN() {
        return egn;
    }

    /**
     * Sets the value of the egn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEGN(String value) {
        this.egn = value;
    }

}
