//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.21 at 12:08:20 PM EEST 
//


package com.bulpros.integrations.regix.model.GRAO.MaritalStatusSpouseChildrenSearch;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RelativeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RelativeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="СЪПРУГ"/&gt;
 *     &lt;enumeration value="СЪПРУГА"/&gt;
 *     &lt;enumeration value="ДЪЩЕРЯ"/&gt;
 *     &lt;enumeration value="СИН"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "RelativeType")
@XmlEnum
public enum RelativeType {

    СЪПРУГ,
    СЪПРУГА,
    ДЪЩЕРЯ,
    СИН;

    public String value() {
        return name();
    }

    public static RelativeType fromValue(String v) {
        return valueOf(v);
    }

}
