//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.18 at 03:52:47 PM EEST 
//


package com.bulpros.integrations.regix.model.MVR.GetPersonalIdentityV3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.*;


/**
 * Данни за справка за лице по документ за самоличност
 * 
 * <p>Java class for PersonalIdentityInfoResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonalIdentityInfoResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ReturnInformations" type="{http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoResponse}ReturnInformation" minOccurs="0"/&gt;
 *         &lt;element name="EGN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PersonNames" type="{http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoResponse}PersonNames" minOccurs="0"/&gt;
 *         &lt;element name="DLCategоries" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="DLCategory" type="{http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoResponse}DLCategory" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DLCommonRestrictions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DataForeignCitizen" type="{http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoResponse}ForeignCitizenType" minOccurs="0"/&gt;
 *         &lt;element name="RPRemarks" type="{http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoResponse}RPRemarkType" minOccurs="0"/&gt;
 *         &lt;element name="RPTypeofPermit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DocumentType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DocumentTypeLatin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DocumentActualStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ActualStatusDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="DocumentStatusReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IdentityDocumentNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IssueDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="IssuerPlace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IssuerPlaceLatin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IssuerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IssuerNameLatin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ValidDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="BirthDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="BirthPlace" type="{http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoResponse}BirthPlace" minOccurs="0"/&gt;
 *         &lt;element name="GenderName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="GenderNameLatin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NationalityList" type="{http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoResponse}NationalityList" minOccurs="0"/&gt;
 *         &lt;element name="PermanentAddress" type="{http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoResponse}PermanentAddress" minOccurs="0"/&gt;
 *         &lt;element name="Height" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="EyesColor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Picture" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="IdentitySignature" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonalIdentityInfoResponseType", propOrder = {
    "returnInformations",
    "egn",
    "personNames",
    "dlCateg\u043eries",
    "dlCommonRestrictions",
    "dataForeignCitizen",
    "rpRemarks",
    "rpTypeofPermit",
    "documentType",
    "documentTypeLatin",
    "documentActualStatus",
    "actualStatusDate",
    "documentStatusReason",
    "identityDocumentNumber",
    "issueDate",
    "issuerPlace",
    "issuerPlaceLatin",
    "issuerName",
    "issuerNameLatin",
    "validDate",
    "birthDate",
    "birthPlace",
    "genderName",
    "genderNameLatin",
    "nationalityList",
    "permanentAddress",
    "height",
    "eyesColor",
    "picture",
    "identitySignature"
})
@XmlRootElement(name = "PersonalIdentityInfoResponse", namespace = "http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoResponse")
public class PersonalIdentityInfoResponseType {

    @XmlElement(name = "ReturnInformations")
    protected ReturnInformation returnInformations;
    @XmlElement(name = "EGN")
    protected String egn;
    @XmlElement(name = "PersonNames")
    protected PersonNames personNames;
    @XmlElement(name = "DLCateg\u043eries")
    protected PersonalIdentityInfoResponseType.DLCategоries dlCategоries;
    @XmlElement(name = "DLCommonRestrictions")
    protected String dlCommonRestrictions;
    @XmlElement(name = "DataForeignCitizen")
    protected ForeignCitizenType dataForeignCitizen;
    @XmlElement(name = "RPRemarks")
    protected RPRemarkType rpRemarks;
    @XmlElement(name = "RPTypeofPermit")
    protected String rpTypeofPermit;
    @XmlElement(name = "DocumentType")
    protected String documentType;
    @XmlElement(name = "DocumentTypeLatin")
    protected String documentTypeLatin;
    @XmlElement(name = "DocumentActualStatus")
    protected String documentActualStatus;
    @XmlElement(name = "ActualStatusDate")
    protected String actualStatusDate;
    @XmlElement(name = "DocumentStatusReason")
    protected String documentStatusReason;
    @XmlElement(name = "IdentityDocumentNumber")
    protected String identityDocumentNumber;
    @XmlElement(name = "IssueDate")
    protected String issueDate;
    @XmlElement(name = "IssuerPlace")
    protected String issuerPlace;
    @XmlElement(name = "IssuerPlaceLatin")
    protected String issuerPlaceLatin;
    @XmlElement(name = "IssuerName")
    protected String issuerName;
    @XmlElement(name = "IssuerNameLatin")
    protected String issuerNameLatin;
    @XmlElement(name = "ValidDate")
    protected String validDate;
    @XmlElement(name = "BirthDate")
    protected String birthDate;
    @XmlElement(name = "BirthPlace")
    protected BirthPlace birthPlace;
    @XmlElement(name = "GenderName")
    protected String genderName;
    @XmlElement(name = "GenderNameLatin")
    protected String genderNameLatin;
    @XmlElement(name = "NationalityList")
    protected NationalityList nationalityList;
    @XmlElement(name = "PermanentAddress")
    protected PermanentAddress permanentAddress;
    @XmlElement(name = "Height")
    protected Double height;
    @XmlElement(name = "EyesColor")
    protected String eyesColor;
    @XmlElement(name = "Picture")
    protected byte[] picture;
    @XmlElement(name = "IdentitySignature")
    protected byte[] identitySignature;

    /**
     * Gets the value of the returnInformations property.
     * 
     * @return
     *     possible object is
     *     {@link ReturnInformation }
     *     
     */
    public ReturnInformation getReturnInformations() {
        return returnInformations;
    }

    /**
     * Sets the value of the returnInformations property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReturnInformation }
     *     
     */
    public void setReturnInformations(ReturnInformation value) {
        this.returnInformations = value;
    }

    /**
     * Gets the value of the egn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEGN() {
        return egn;
    }

    /**
     * Sets the value of the egn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEGN(String value) {
        this.egn = value;
    }

    /**
     * Gets the value of the personNames property.
     * 
     * @return
     *     possible object is
     *     {@link PersonNames }
     *     
     */
    public PersonNames getPersonNames() {
        return personNames;
    }

    /**
     * Sets the value of the personNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonNames }
     *     
     */
    public void setPersonNames(PersonNames value) {
        this.personNames = value;
    }

    /**
     * Gets the value of the dlCategоries property.
     * 
     * @return
     *     possible object is
     *     {@link PersonalIdentityInfoResponseType.DLCategоries }
     *     
     */
    public PersonalIdentityInfoResponseType.DLCategоries getDLCategоries() {
        return dlCategоries;
    }

    /**
     * Sets the value of the dlCategоries property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonalIdentityInfoResponseType.DLCategоries }
     *     
     */
    public void setDLCategоries(PersonalIdentityInfoResponseType.DLCategоries value) {
        this.dlCategоries = value;
    }

    /**
     * Gets the value of the dlCommonRestrictions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDLCommonRestrictions() {
        return dlCommonRestrictions;
    }

    /**
     * Sets the value of the dlCommonRestrictions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDLCommonRestrictions(String value) {
        this.dlCommonRestrictions = value;
    }

    /**
     * Gets the value of the dataForeignCitizen property.
     * 
     * @return
     *     possible object is
     *     {@link ForeignCitizenType }
     *     
     */
    public ForeignCitizenType getDataForeignCitizen() {
        return dataForeignCitizen;
    }

    /**
     * Sets the value of the dataForeignCitizen property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForeignCitizenType }
     *     
     */
    public void setDataForeignCitizen(ForeignCitizenType value) {
        this.dataForeignCitizen = value;
    }

    /**
     * Gets the value of the rpRemarks property.
     * 
     * @return
     *     possible object is
     *     {@link RPRemarkType }
     *     
     */
    public RPRemarkType getRPRemarks() {
        return rpRemarks;
    }

    /**
     * Sets the value of the rpRemarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link RPRemarkType }
     *     
     */
    public void setRPRemarks(RPRemarkType value) {
        this.rpRemarks = value;
    }

    /**
     * Gets the value of the rpTypeofPermit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRPTypeofPermit() {
        return rpTypeofPermit;
    }

    /**
     * Sets the value of the rpTypeofPermit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRPTypeofPermit(String value) {
        this.rpTypeofPermit = value;
    }

    /**
     * Gets the value of the documentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentType(String value) {
        this.documentType = value;
    }

    /**
     * Gets the value of the documentTypeLatin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentTypeLatin() {
        return documentTypeLatin;
    }

    /**
     * Sets the value of the documentTypeLatin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentTypeLatin(String value) {
        this.documentTypeLatin = value;
    }

    /**
     * Gets the value of the documentActualStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentActualStatus() {
        return documentActualStatus;
    }

    /**
     * Sets the value of the documentActualStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentActualStatus(String value) {
        this.documentActualStatus = value;
    }

    /**
     * Gets the value of the actualStatusDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActualStatusDate() {
        return actualStatusDate;
    }

    /**
     * Sets the value of the actualStatusDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActualStatusDate(String value) {
        this.actualStatusDate = value;
    }

    /**
     * Gets the value of the documentStatusReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentStatusReason() {
        return documentStatusReason;
    }

    /**
     * Sets the value of the documentStatusReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentStatusReason(String value) {
        this.documentStatusReason = value;
    }

    /**
     * Gets the value of the identityDocumentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentityDocumentNumber() {
        return identityDocumentNumber;
    }

    /**
     * Sets the value of the identityDocumentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentityDocumentNumber(String value) {
        this.identityDocumentNumber = value;
    }

    /**
     * Gets the value of the issueDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueDate() {
        return issueDate;
    }

    /**
     * Sets the value of the issueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueDate(String value) {
        this.issueDate = value;
    }

    /**
     * Gets the value of the issuerPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuerPlace() {
        return issuerPlace;
    }

    /**
     * Sets the value of the issuerPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuerPlace(String value) {
        this.issuerPlace = value;
    }

    /**
     * Gets the value of the issuerPlaceLatin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuerPlaceLatin() {
        return issuerPlaceLatin;
    }

    /**
     * Sets the value of the issuerPlaceLatin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuerPlaceLatin(String value) {
        this.issuerPlaceLatin = value;
    }

    /**
     * Gets the value of the issuerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuerName() {
        return issuerName;
    }

    /**
     * Sets the value of the issuerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuerName(String value) {
        this.issuerName = value;
    }

    /**
     * Gets the value of the issuerNameLatin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuerNameLatin() {
        return issuerNameLatin;
    }

    /**
     * Sets the value of the issuerNameLatin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuerNameLatin(String value) {
        this.issuerNameLatin = value;
    }

    /**
     * Gets the value of the validDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidDate() {
        return validDate;
    }

    /**
     * Sets the value of the validDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidDate(String value) {
        this.validDate = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBirthDate(String value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the birthPlace property.
     * 
     * @return
     *     possible object is
     *     {@link BirthPlace }
     *     
     */
    public BirthPlace getBirthPlace() {
        return birthPlace;
    }

    /**
     * Sets the value of the birthPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link BirthPlace }
     *     
     */
    public void setBirthPlace(BirthPlace value) {
        this.birthPlace = value;
    }

    /**
     * Gets the value of the genderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenderName() {
        return genderName;
    }

    /**
     * Sets the value of the genderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenderName(String value) {
        this.genderName = value;
    }

    /**
     * Gets the value of the genderNameLatin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenderNameLatin() {
        return genderNameLatin;
    }

    /**
     * Sets the value of the genderNameLatin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenderNameLatin(String value) {
        this.genderNameLatin = value;
    }

    /**
     * Gets the value of the nationalityList property.
     * 
     * @return
     *     possible object is
     *     {@link NationalityList }
     *     
     */
    public NationalityList getNationalityList() {
        return nationalityList;
    }

    /**
     * Sets the value of the nationalityList property.
     * 
     * @param value
     *     allowed object is
     *     {@link NationalityList }
     *     
     */
    public void setNationalityList(NationalityList value) {
        this.nationalityList = value;
    }

    /**
     * Gets the value of the permanentAddress property.
     * 
     * @return
     *     possible object is
     *     {@link PermanentAddress }
     *     
     */
    public PermanentAddress getPermanentAddress() {
        return permanentAddress;
    }

    /**
     * Sets the value of the permanentAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link PermanentAddress }
     *     
     */
    public void setPermanentAddress(PermanentAddress value) {
        this.permanentAddress = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setHeight(Double value) {
        this.height = value;
    }

    /**
     * Gets the value of the eyesColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEyesColor() {
        return eyesColor;
    }

    /**
     * Sets the value of the eyesColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEyesColor(String value) {
        this.eyesColor = value;
    }

    /**
     * Gets the value of the picture property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getPicture() {
        return picture;
    }

    /**
     * Sets the value of the picture property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setPicture(byte[] value) {
        this.picture = value;
    }

    /**
     * Gets the value of the identitySignature property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getIdentitySignature() {
        return identitySignature;
    }

    /**
     * Sets the value of the identitySignature property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setIdentitySignature(byte[] value) {
        this.identitySignature = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="DLCategory" type="{http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoResponse}DLCategory" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dlCategory"
    })
    public static class DLCategоries {

        @XmlElement(name = "DLCategory")
        protected List<DLCategory> dlCategory;

        /**
         * Gets the value of the dlCategory property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dlCategory property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDLCategory().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DLCategory }
         * 
         * 
         */
        public List<DLCategory> getDLCategory() {
            if (dlCategory == null) {
                dlCategory = new ArrayList<DLCategory>();
            }
            return this.dlCategory;
        }

    }

}
