//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.26 at 07:37:27 PM EEST 
//


package com.bulpros.integrations.regix.model.MVR.GetMotorVehicleRegistrationInfo;

import javax.xml.bind.annotation.*;


/**
 * Данни за справка на данни от свидетелство за регистрация на МПС (част 2) 
 * 
 * <p>Java class for MotorVehicleRegistrationResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MotorVehicleRegistrationResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ReturnInformation" type="{http://egov.bg/RegiX/MVR/MPS/MotorVehicleRegistrationResponse}ReturnInformation" minOccurs="0"/&gt;
 *         &lt;element name="Vehicles" type="{http://egov.bg/RegiX/MVR/MPS/MotorVehicleRegistrationResponse}Vehicles" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MotorVehicleRegistrationResponseType", propOrder = {
    "returnInformation",
    "vehicles"
})
@XmlRootElement(name = "MotorVehicleRegistrationResponse", namespace = "http://egov.bg/RegiX/MVR/MPS/MotorVehicleRegistrationResponse")
public class MotorVehicleRegistrationResponseType {

    @XmlElement(name = "ReturnInformation")
    protected ReturnInformation returnInformation;
    @XmlElement(name = "Vehicles")
    protected Vehicles vehicles;

    /**
     * Gets the value of the returnInformation property.
     * 
     * @return
     *     possible object is
     *     {@link ReturnInformation }
     *     
     */
    public ReturnInformation getReturnInformation() {
        return returnInformation;
    }

    /**
     * Sets the value of the returnInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReturnInformation }
     *     
     */
    public void setReturnInformation(ReturnInformation value) {
        this.returnInformation = value;
    }

    /**
     * Gets the value of the vehicles property.
     * 
     * @return
     *     possible object is
     *     {@link Vehicles }
     *     
     */
    public Vehicles getVehicles() {
        return vehicles;
    }

    /**
     * Sets the value of the vehicles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vehicles }
     *     
     */
    public void setVehicles(Vehicles value) {
        this.vehicles = value;
    }

}
