//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.26 at 07:37:27 PM EEST 
//


package com.bulpros.integrations.regix.model.MVR.GetMotorVehicleRegistrationInfo;

import javax.xml.bind.annotation.*;


/**
 * Входни данни за справка от свидетелство за регистрация на МПС (част 2)
 * 
 * <p>Java class for MotorVehicleRegistrationRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MotorVehicleRegistrationRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Identifier" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MotorVehicleRegistrationRequestType", namespace = "http://egov.bg/RegiX/MVR/MPS/MotorVehicleRegistrationRequest", propOrder = {
    "identifier"
})
@XmlRootElement(name = "MotorVehicleRegistrationRequest", namespace = "http://egov.bg/RegiX/MVR/MPS/MotorVehicleRegistrationRequest")
public class MotorVehicleRegistrationRequestType {

    @XmlElement(name = "Identifier", required = true)
    protected String identifier;

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

}
