//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.26 at 07:37:27 PM EEST 
//


package com.bulpros.integrations.regix.model.MVR.GetMotorVehicleRegistrationInfo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Данни за МПС
 * 
 * <p>Java class for Vehicle complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Vehicle"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="VehicleRegistrationNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FirstRegistrationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="MotorVehicleRegistrationCertificateNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OwnerPersonData" type="{http://egov.bg/RegiX/MVR/MPS/MotorVehicleRegistrationResponse}PersonData" minOccurs="0"/&gt;
 *         &lt;element name="OwnerEntityData" type="{http://egov.bg/RegiX/MVR/MPS/MotorVehicleRegistrationResponse}EntityData" minOccurs="0"/&gt;
 *         &lt;element name="OwnerForeignerPersonData" type="{http://egov.bg/RegiX/MVR/MPS/MotorVehicleRegistrationResponse}ForeignerPersonData" minOccurs="0"/&gt;
 *         &lt;element name="MotorVehicleType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MotorVehicleTypeLatin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MotorVehicleModel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MotorVehicleModelLatin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MotorVehicleModelType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TradeDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TradeDescriptionLatin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="VINNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IssueDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Color" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ColorLatin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EngineNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ColorSecondary" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ColorSecondaryLatin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Vehicle", propOrder = {
    "vehicleRegistrationNumber",
    "firstRegistrationDate",
    "motorVehicleRegistrationCertificateNumber",
    "ownerPersonData",
    "ownerEntityData",
    "ownerForeignerPersonData",
    "motorVehicleType",
    "motorVehicleTypeLatin",
    "motorVehicleModel",
    "motorVehicleModelLatin",
    "motorVehicleModelType",
    "tradeDescription",
    "tradeDescriptionLatin",
    "vinNumber",
    "issueDate",
    "category",
    "color",
    "colorLatin",
    "engineNumber",
    "colorSecondary",
    "colorSecondaryLatin"
})
public class Vehicle {

    @XmlElement(name = "VehicleRegistrationNumber")
    protected String vehicleRegistrationNumber;
    @XmlElement(name = "FirstRegistrationDate")
    protected String firstRegistrationDate;
    @XmlElement(name = "MotorVehicleRegistrationCertificateNumber")
    protected String motorVehicleRegistrationCertificateNumber;
    @XmlElement(name = "OwnerPersonData")
    protected PersonData ownerPersonData;
    @XmlElement(name = "OwnerEntityData")
    protected EntityData ownerEntityData;
    @XmlElement(name = "OwnerForeignerPersonData")
    protected ForeignerPersonData ownerForeignerPersonData;
    @XmlElement(name = "MotorVehicleType")
    protected String motorVehicleType;
    @XmlElement(name = "MotorVehicleTypeLatin")
    protected String motorVehicleTypeLatin;
    @XmlElement(name = "MotorVehicleModel")
    protected String motorVehicleModel;
    @XmlElement(name = "MotorVehicleModelLatin")
    protected String motorVehicleModelLatin;
    @XmlElement(name = "MotorVehicleModelType")
    protected String motorVehicleModelType;
    @XmlElement(name = "TradeDescription")
    protected String tradeDescription;
    @XmlElement(name = "TradeDescriptionLatin")
    protected String tradeDescriptionLatin;
    @XmlElement(name = "VINNumber")
    protected String vinNumber;
    @XmlElement(name = "IssueDate")
    protected String issueDate;
    @XmlElement(name = "Category")
    protected String category;
    @XmlElement(name = "Color")
    protected String color;
    @XmlElement(name = "ColorLatin")
    protected String colorLatin;
    @XmlElement(name = "EngineNumber")
    protected String engineNumber;
    @XmlElement(name = "ColorSecondary")
    protected String colorSecondary;
    @XmlElement(name = "ColorSecondaryLatin")
    protected String colorSecondaryLatin;

    /**
     * Gets the value of the vehicleRegistrationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleRegistrationNumber() {
        return vehicleRegistrationNumber;
    }

    /**
     * Sets the value of the vehicleRegistrationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleRegistrationNumber(String value) {
        this.vehicleRegistrationNumber = value;
    }

    /**
     * Gets the value of the firstRegistrationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstRegistrationDate() {
        return firstRegistrationDate;
    }

    /**
     * Sets the value of the firstRegistrationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstRegistrationDate(String value) {
        this.firstRegistrationDate = value;
    }

    /**
     * Gets the value of the motorVehicleRegistrationCertificateNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMotorVehicleRegistrationCertificateNumber() {
        return motorVehicleRegistrationCertificateNumber;
    }

    /**
     * Sets the value of the motorVehicleRegistrationCertificateNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMotorVehicleRegistrationCertificateNumber(String value) {
        this.motorVehicleRegistrationCertificateNumber = value;
    }

    /**
     * Gets the value of the ownerPersonData property.
     * 
     * @return
     *     possible object is
     *     {@link PersonData }
     *     
     */
    public PersonData getOwnerPersonData() {
        return ownerPersonData;
    }

    /**
     * Sets the value of the ownerPersonData property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonData }
     *     
     */
    public void setOwnerPersonData(PersonData value) {
        this.ownerPersonData = value;
    }

    /**
     * Gets the value of the ownerEntityData property.
     * 
     * @return
     *     possible object is
     *     {@link EntityData }
     *     
     */
    public EntityData getOwnerEntityData() {
        return ownerEntityData;
    }

    /**
     * Sets the value of the ownerEntityData property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityData }
     *     
     */
    public void setOwnerEntityData(EntityData value) {
        this.ownerEntityData = value;
    }

    /**
     * Gets the value of the ownerForeignerPersonData property.
     * 
     * @return
     *     possible object is
     *     {@link ForeignerPersonData }
     *     
     */
    public ForeignerPersonData getOwnerForeignerPersonData() {
        return ownerForeignerPersonData;
    }

    /**
     * Sets the value of the ownerForeignerPersonData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForeignerPersonData }
     *     
     */
    public void setOwnerForeignerPersonData(ForeignerPersonData value) {
        this.ownerForeignerPersonData = value;
    }

    /**
     * Gets the value of the motorVehicleType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMotorVehicleType() {
        return motorVehicleType;
    }

    /**
     * Sets the value of the motorVehicleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMotorVehicleType(String value) {
        this.motorVehicleType = value;
    }

    /**
     * Gets the value of the motorVehicleTypeLatin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMotorVehicleTypeLatin() {
        return motorVehicleTypeLatin;
    }

    /**
     * Sets the value of the motorVehicleTypeLatin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMotorVehicleTypeLatin(String value) {
        this.motorVehicleTypeLatin = value;
    }

    /**
     * Gets the value of the motorVehicleModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMotorVehicleModel() {
        return motorVehicleModel;
    }

    /**
     * Sets the value of the motorVehicleModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMotorVehicleModel(String value) {
        this.motorVehicleModel = value;
    }

    /**
     * Gets the value of the motorVehicleModelLatin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMotorVehicleModelLatin() {
        return motorVehicleModelLatin;
    }

    /**
     * Sets the value of the motorVehicleModelLatin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMotorVehicleModelLatin(String value) {
        this.motorVehicleModelLatin = value;
    }

    /**
     * Gets the value of the motorVehicleModelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMotorVehicleModelType() {
        return motorVehicleModelType;
    }

    /**
     * Sets the value of the motorVehicleModelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMotorVehicleModelType(String value) {
        this.motorVehicleModelType = value;
    }

    /**
     * Gets the value of the tradeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradeDescription() {
        return tradeDescription;
    }

    /**
     * Sets the value of the tradeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradeDescription(String value) {
        this.tradeDescription = value;
    }

    /**
     * Gets the value of the tradeDescriptionLatin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradeDescriptionLatin() {
        return tradeDescriptionLatin;
    }

    /**
     * Sets the value of the tradeDescriptionLatin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradeDescriptionLatin(String value) {
        this.tradeDescriptionLatin = value;
    }

    /**
     * Gets the value of the vinNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVINNumber() {
        return vinNumber;
    }

    /**
     * Sets the value of the vinNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVINNumber(String value) {
        this.vinNumber = value;
    }

    /**
     * Gets the value of the issueDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueDate() {
        return issueDate;
    }

    /**
     * Sets the value of the issueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueDate(String value) {
        this.issueDate = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the colorLatin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColorLatin() {
        return colorLatin;
    }

    /**
     * Sets the value of the colorLatin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColorLatin(String value) {
        this.colorLatin = value;
    }

    /**
     * Gets the value of the engineNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEngineNumber() {
        return engineNumber;
    }

    /**
     * Sets the value of the engineNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEngineNumber(String value) {
        this.engineNumber = value;
    }

    /**
     * Gets the value of the colorSecondary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColorSecondary() {
        return colorSecondary;
    }

    /**
     * Sets the value of the colorSecondary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColorSecondary(String value) {
        this.colorSecondary = value;
    }

    /**
     * Gets the value of the colorSecondaryLatin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColorSecondaryLatin() {
        return colorSecondaryLatin;
    }

    /**
     * Sets the value of the colorSecondaryLatin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColorSecondaryLatin(String value) {
        this.colorSecondaryLatin = value;
    }

}
