//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.26 at 07:37:25 PM EEST 
//


package com.bulpros.integrations.regix.model.GRAO.PersonDataSearch;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GenderNameType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="GenderNameType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Мъж"/&gt;
 *     &lt;enumeration value="Жена"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "GenderNameType")
@XmlEnum
public enum GenderNameType {

    @XmlEnumValue("\u041c\u044a\u0436")
    МЪЖ("\u041c\u044a\u0436"),
    @XmlEnumValue("\u0416\u0435\u043d\u0430")
    ЖЕНА("\u0416\u0435\u043d\u0430");
    private final String value;

    GenderNameType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GenderNameType fromValue(String v) {
        for (GenderNameType c: GenderNameType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
