//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 04:57:02 PM EEST 
//


package com.bulpros.integrations.regix.model.GRAO.PersonDataSearch;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for PersonDataResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonDataResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PersonNames" type="{http://egov.bg/RegiX/GRAO/NBD}PersonNames" minOccurs="0"/&gt;
 *         &lt;element name="Alias" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LatinNames" type="{http://egov.bg/RegiX/GRAO/NBD}PersonNames" minOccurs="0"/&gt;
 *         &lt;element name="ForeignNames" type="{http://egov.bg/RegiX/GRAO/NBD}PersonNames" minOccurs="0"/&gt;
 *         &lt;element name="Gender" type="{http://egov.bg/RegiX/GRAO/NBD}Gender" minOccurs="0"/&gt;
 *         &lt;element name="EGN" type="{http://egov.bg/RegiX/GRAO/NBD}EGN" minOccurs="0"/&gt;
 *         &lt;element name="BirthDate" type="{http://egov.bg/RegiX/GRAO/NBD}BirthDate" minOccurs="0"/&gt;
 *         &lt;element name="PlaceBirth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Nationality" type="{http://egov.bg/RegiX/GRAO/NBD}Nationality" minOccurs="0"/&gt;
 *         &lt;element name="DeathDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonDataResponseType", namespace = "http://egov.bg/RegiX/GRAO/NBD/PersonDataResponse", propOrder = {
    "personNames",
    "alias",
    "latinNames",
    "foreignNames",
    "gender",
    "egn",
    "birthDate",
    "placeBirth",
    "nationality",
    "deathDate"
})
@XmlRootElement(name = "PersonDataResponse", namespace = "http://egov.bg/RegiX/GRAO/NBD/PersonDataResponse")
public class PersonDataResponseType {

    @XmlElement(name = "PersonNames")
    protected PersonNames personNames;
    @XmlElement(name = "Alias")
    protected String alias;
    @XmlElement(name = "LatinNames")
    protected PersonNames latinNames;
    @XmlElement(name = "ForeignNames")
    protected PersonNames foreignNames;
    @XmlElement(name = "Gender")
    protected Gender gender;
    @XmlElement(name = "EGN")
    protected String egn;
    @XmlElement(name = "BirthDate")
    protected String birthDate;
    @XmlElement(name = "PlaceBirth")
    protected String placeBirth;
    @XmlElement(name = "Nationality")
    protected Nationality nationality;
    @XmlElement(name = "DeathDate")
    protected String deathDate;

    /**
     * Gets the value of the personNames property.
     * 
     * @return
     *     possible object is
     *     {@link PersonNames }
     *     
     */
    public PersonNames getPersonNames() {
        return personNames;
    }

    /**
     * Sets the value of the personNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonNames }
     *     
     */
    public void setPersonNames(PersonNames value) {
        this.personNames = value;
    }

    /**
     * Gets the value of the alias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlias() {
        return alias;
    }

    /**
     * Sets the value of the alias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlias(String value) {
        this.alias = value;
    }

    /**
     * Gets the value of the latinNames property.
     * 
     * @return
     *     possible object is
     *     {@link PersonNames }
     *     
     */
    public PersonNames getLatinNames() {
        return latinNames;
    }

    /**
     * Sets the value of the latinNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonNames }
     *     
     */
    public void setLatinNames(PersonNames value) {
        this.latinNames = value;
    }

    /**
     * Gets the value of the foreignNames property.
     * 
     * @return
     *     possible object is
     *     {@link PersonNames }
     *     
     */
    public PersonNames getForeignNames() {
        return foreignNames;
    }

    /**
     * Sets the value of the foreignNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonNames }
     *     
     */
    public void setForeignNames(PersonNames value) {
        this.foreignNames = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link Gender }
     *     
     */
    public Gender getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link Gender }
     *     
     */
    public void setGender(Gender value) {
        this.gender = value;
    }

    /**
     * Gets the value of the egn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEGN() {
        return egn;
    }

    /**
     * Sets the value of the egn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEGN(String value) {
        this.egn = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBirthDate(String value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the placeBirth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaceBirth() {
        return placeBirth;
    }

    /**
     * Sets the value of the placeBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaceBirth(String value) {
        this.placeBirth = value;
    }

    /**
     * Gets the value of the nationality property.
     * 
     * @return
     *     possible object is
     *     {@link Nationality }
     *     
     */
    public Nationality getNationality() {
        return nationality;
    }

    /**
     * Sets the value of the nationality property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nationality }
     *     
     */
    public void setNationality(Nationality value) {
        this.nationality = value;
    }

    /**
     * Gets the value of the deathDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeathDate() {
        return deathDate;
    }

    /**
     * Sets the value of the deathDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeathDate(String value) {
        this.deathDate = value;
    }

}
