package com.bulpros.integrations.regix.model.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2022-02-28T14:58:20.435+02:00
 * Generated source version: 3.4.3
 *
 */
@WebService(targetNamespace = "http://egov.bg/RegiX", name = "IRegiXEntryPointV2")
@XmlSeeAlso({ObjectFactory.class})
public interface IRegiXEntryPointV2 {

    @WebMethod(operationName = "CheckResult", action = "http://egov.bg/RegiX/IRegiXEntryPointV2/CheckResult")
    @Action(input = "http://egov.bg/RegiX/IRegiXEntryPointV2/CheckResult", output = "http://egov.bg/RegiX/IRegiXEntryPointV2/CheckResultResponse")
    @RequestWrapper(localName = "CheckResult", targetNamespace = "http://egov.bg/RegiX", className = "com.bulpros.integrations.regix.model.client.CheckResult")
    @ResponseWrapper(localName = "CheckResultResponse", targetNamespace = "http://egov.bg/RegiX", className = "com.bulpros.integrations.regix.model.client.CheckResultResponse")
    @WebResult(name = "CheckResultResult", targetNamespace = "http://egov.bg/RegiX")
    public com.bulpros.integrations.regix.model.client.ResultWrapper checkResult(

        @WebParam(name = "argument", targetNamespace = "http://egov.bg/RegiX")
        com.bulpros.integrations.regix.model.client.ServiceCheckResultWrapper argument
    );

    @WebMethod(operationName = "Execute", action = "http://egov.bg/RegiX/IRegiXEntryPointV2/Execute")
    @Action(input = "http://egov.bg/RegiX/IRegiXEntryPointV2/Execute", output = "http://egov.bg/RegiX/IRegiXEntryPointV2/ExecuteResponse")
    @RequestWrapper(localName = "Execute", targetNamespace = "http://egov.bg/RegiX", className = "com.bulpros.integrations.regix.model.client.Execute")
    @ResponseWrapper(localName = "ExecuteResponse", targetNamespace = "http://egov.bg/RegiX", className = "com.bulpros.integrations.regix.model.client.ExecuteResponse")
    @WebResult(name = "ExecuteResult", targetNamespace = "http://egov.bg/RegiX")
    public com.bulpros.integrations.regix.model.client.ResultWrapper execute(

        @WebParam(name = "request", targetNamespace = "http://egov.bg/RegiX")
        com.bulpros.integrations.regix.model.client.RequestWrapper request
    );

    @WebMethod(operationName = "ExecuteCallback", action = "http://egov.bg/RegiX/IRegiXEntryPointV2/ExecuteCallback")
    @Action(input = "http://egov.bg/RegiX/IRegiXEntryPointV2/ExecuteCallback", output = "http://egov.bg/RegiX/IRegiXEntryPointV2/ExecuteCallbackResponse")
    @RequestWrapper(localName = "ExecuteCallback", targetNamespace = "http://egov.bg/RegiX", className = "com.bulpros.integrations.regix.model.client.ExecuteCallback")
    @ResponseWrapper(localName = "ExecuteCallbackResponse", targetNamespace = "http://egov.bg/RegiX", className = "com.bulpros.integrations.regix.model.client.ExecuteCallbackResponse")
    public void executeCallback(

        @WebParam(name = "request", targetNamespace = "http://egov.bg/RegiX")
        com.bulpros.integrations.regix.model.client.ResultWrapper request
    );

    @WebMethod(operationName = "AcknowledgeResultReceived", action = "http://egov.bg/RegiX/IRegiXEntryPointV2/AcknowledgeResultReceived")
    @Action(input = "http://egov.bg/RegiX/IRegiXEntryPointV2/AcknowledgeResultReceived", output = "http://egov.bg/RegiX/IRegiXEntryPointV2/AcknowledgeResultReceivedResponse")
    @RequestWrapper(localName = "AcknowledgeResultReceived", targetNamespace = "http://egov.bg/RegiX", className = "com.bulpros.integrations.regix.model.client.AcknowledgeResultReceived")
    @ResponseWrapper(localName = "AcknowledgeResultReceivedResponse", targetNamespace = "http://egov.bg/RegiX", className = "com.bulpros.integrations.regix.model.client.AcknowledgeResultReceivedResponse")
    public void acknowledgeResultReceived(

        @WebParam(name = "argument", targetNamespace = "http://egov.bg/RegiX")
        com.bulpros.integrations.regix.model.client.ServiceCheckResultWrapper argument
    );
}
