package com.bulpros.integrations.regix.model.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2022-02-28T14:58:20.473+02:00
 * Generated source version: 3.4.3
 *
 */
@WebServiceClient(name = "RegiXEntryPointV2",
                  wsdlLocation = "https://service-regix.egov.bg/RegiXEntryPointV2.svc.singlewsdl.xml",
                  targetNamespace = "http://egov.bg/RegiX")
public class RegiXEntryPointV2 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://egov.bg/RegiX", "RegiXEntryPointV2");
    public final static QName WSHttpBindingIRegiXEntryPointV2 = new QName("http://egov.bg/RegiX", "WSHttpBinding_IRegiXEntryPointV2");
    public final static QName BasicHttpBindingIRegiXEntryPointV21 = new QName("http://egov.bg/RegiX", "BasicHttpBinding_IRegiXEntryPointV21");
    public final static QName BasicHttpBindingIRegiXEntryPointV2 = new QName("http://egov.bg/RegiX", "BasicHttpBinding_IRegiXEntryPointV2");
    static {
        URL url = null;
        try {
            url = new URL("https://service-regix.egov.bg/RegiXEntryPointV2.svc.singlewsdl.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RegiXEntryPointV2.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://service-regix.egov.bg/RegiXEntryPointV2.svc.singlewsdl.xml");
        }
        WSDL_LOCATION = url;
    }

    public RegiXEntryPointV2(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RegiXEntryPointV2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegiXEntryPointV2() {
        super(WSDL_LOCATION, SERVICE);
    }

    public RegiXEntryPointV2(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RegiXEntryPointV2(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RegiXEntryPointV2(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IRegiXEntryPointV2
     */
    @WebEndpoint(name = "WSHttpBinding_IRegiXEntryPointV2")
    public IRegiXEntryPointV2 getWSHttpBindingIRegiXEntryPointV2() {
        return super.getPort(WSHttpBindingIRegiXEntryPointV2, IRegiXEntryPointV2.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IRegiXEntryPointV2
     */
    @WebEndpoint(name = "WSHttpBinding_IRegiXEntryPointV2")
    public IRegiXEntryPointV2 getWSHttpBindingIRegiXEntryPointV2(WebServiceFeature... features) {
        return super.getPort(WSHttpBindingIRegiXEntryPointV2, IRegiXEntryPointV2.class, features);
    }


    /**
     *
     * @return
     *     returns IRegiXEntryPointV2
     */
    @WebEndpoint(name = "BasicHttpBinding_IRegiXEntryPointV21")
    public IRegiXEntryPointV2 getBasicHttpBindingIRegiXEntryPointV21() {
        return super.getPort(BasicHttpBindingIRegiXEntryPointV21, IRegiXEntryPointV2.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IRegiXEntryPointV2
     */
    @WebEndpoint(name = "BasicHttpBinding_IRegiXEntryPointV21")
    public IRegiXEntryPointV2 getBasicHttpBindingIRegiXEntryPointV21(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIRegiXEntryPointV21, IRegiXEntryPointV2.class, features);
    }


    /**
     *
     * @return
     *     returns IRegiXEntryPointV2
     */
    @WebEndpoint(name = "BasicHttpBinding_IRegiXEntryPointV2")
    public IRegiXEntryPointV2 getBasicHttpBindingIRegiXEntryPointV2() {
        return super.getPort(BasicHttpBindingIRegiXEntryPointV2, IRegiXEntryPointV2.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IRegiXEntryPointV2
     */
    @WebEndpoint(name = "BasicHttpBinding_IRegiXEntryPointV2")
    public IRegiXEntryPointV2 getBasicHttpBindingIRegiXEntryPointV2(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIRegiXEntryPointV2, IRegiXEntryPointV2.class, features);
    }

}
