pipeline {
    environment {
        DEPLOY = "${env.BRANCH_NAME == "develop" ? "true" : "false"}"
        NAME = "${env.BRANCH_NAME == "develop" ? "example" : "example-staging"}"
       // gitCredentialId = 'EID-Bitbucket' //defined in credentials area
       // gitUrl = 'https://104.192.141.1/intracol/forms-flow-web-mf.git'
       // deployBranch = 'develop'
    }
  
    agent {
      kubernetes {
        yaml '''
          apiVersion: v1
          kind: Pod
          spec:
            containers:
            - name: micro
              image: docker.io/ubuntu:latest
              lifecycle:
              postStart:
                exec:
                  command: ["/bin/sh", "-c", "echo '104.192.141.1 bitbucket.org' >> /etc/hosts"]
              volumeMounts:
                - name: js
                  mountPath: /mnt
              command:
              - cat
              tty: true
            volumes:
            - name: js
              nfs:
                server: 192.168.201.46
                path: /mnt
          '''
      }
    }

    stages {
      stage('Micro FrontEnd WEB') {
          steps {
            container('micro'){                
                sh '''
                apt update
                apt-get install -y  curl
                curl -sL https://deb.nodesource.com/setup_14.x |  bash -
                apt-get install -y  nodejs 
                node -v
                npm install
                npm run build
                rm -rf /mnt/forms-flow-web-mf/*
                mv ./build /mnt/forms-flow-web-mf
                '''              
            }
          }
        }
  }
}
