/**
 * Please follow code style when editing project
 * Please follow principles of clean architecture
 * Created 2023 by Roman Kryvolapov
 **/
package com.digital.sofia.domain.models.common

import com.digital.sofia.domain.models.base.TypeEnum

enum class SdkStatus(override val type: String) : TypeEnum {
    SDK_SETUP_ERROR("SDK_SETUP_ERROR"),
    SDK_SETUP_READY("SDK_SETUP_READY"),
    USER_SETUP_ERROR("USER_SETUP_ERROR"),
    USER_SETUP_READY("USER_SETUP_READY"),
    USER_STATUS_READY("USER_STATUS_READY"),
    USER_STATUS_NOT_IDENTIFIED("USER_STATUS_NOT_IDENTIFIED"),
    USER_STATUS_CALLBACK_READY("USER_STATUS_CALLBACK_READY"),
    USER_SET_UP_ONLINE_READY("USER_SET_UP_ONLINE_READY"),
    CHANGE_SECURITY_CONTEXT_READY("CHANGE_SECURITY_CONTEXT_READY"),
    ACTIVITY_RESULT_SETUP_PROFILE_READY("ACTIVITY_RESULT_SETUP_PROFILE_READY"),
    ACTIVITY_RESULT_SETUP_PROFILE_CANCELLED("ACTIVITY_RESULT_SETUP_PROFILE_CANCELLED"),
    ACTIVITY_RESULT_SETUP_PROFILE_ERROR("ACTIVITY_RESULT_SETUP_PROFILE_ERROR"),
    ACTIVITY_RESULT_OPEN_SINGLE_DOCUMENT_REJECTED("ACTIVITY_RESULT_OPEN_SINGLE_DOCUMENT_REJECTED"),
    ACTIVITY_RESULT_OPEN_SINGLE_DOCUMENT_READY("ACTIVITY_RESULT_OPEN_SINGLE_DOCUMENT_READY"),
    ACTIVITY_RESULT_OPEN_SINGLE_DOCUMENT_CANCELLED("ACTIVITY_RESULT_OPEN_SINGLE_DOCUMENT_CANCELLED"),
    ACTIVITY_RESULT_OPEN_GROUP_DOCUMENTS_READY("ACTIVITY_RESULT_OPEN_GROUP_DOCUMENTS_READY"),
    ACTIVITY_RESULT_EDIT_PERSONAL_DATA_READY("ACTIVITY_RESULT_EDIT_PERSONAL_DATA_READY"),
    CRITICAL_ERROR("CRITICAL_ERROR"),
    ERROR("ERROR"),
}