//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.26 at 07:37:26 PM EEST 
//


package com.bulpros.integrations.regix.model.AV.TR.GetActualState;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LiquidationOrInsolvency.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LiquidationOrInsolvency"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="В ликвидация"/&gt;
 *     &lt;enumeration value="В несъстоятелност"/&gt;
 *     &lt;enumeration value="В несъстоятелност (на II инстанция)"/&gt;
 *     &lt;enumeration value="В несъстоятелност (на III инстанция)"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "LiquidationOrInsolvency", namespace = "http://egov.bg/RegiX/AV/TR/ActualStateResponse")
@XmlEnum
public enum LiquidationOrInsolvency {

    @XmlEnumValue("\u0412 \u043b\u0438\u043a\u0432\u0438\u0434\u0430\u0446\u0438\u044f")
    В_ЛИКВИДАЦИЯ("\u0412 \u043b\u0438\u043a\u0432\u0438\u0434\u0430\u0446\u0438\u044f"),
    @XmlEnumValue("\u0412 \u043d\u0435\u0441\u044a\u0441\u0442\u043e\u044f\u0442\u0435\u043b\u043d\u043e\u0441\u0442")
    В_НЕСЪСТОЯТЕЛНОСТ("\u0412 \u043d\u0435\u0441\u044a\u0441\u0442\u043e\u044f\u0442\u0435\u043b\u043d\u043e\u0441\u0442"),
    @XmlEnumValue("\u0412 \u043d\u0435\u0441\u044a\u0441\u0442\u043e\u044f\u0442\u0435\u043b\u043d\u043e\u0441\u0442 (\u043d\u0430 II \u0438\u043d\u0441\u0442\u0430\u043d\u0446\u0438\u044f)")
    В_НЕСЪСТОЯТЕЛНОСТ_НА_II_ИНСТАНЦИЯ("\u0412 \u043d\u0435\u0441\u044a\u0441\u0442\u043e\u044f\u0442\u0435\u043b\u043d\u043e\u0441\u0442 (\u043d\u0430 II \u0438\u043d\u0441\u0442\u0430\u043d\u0446\u0438\u044f)"),
    @XmlEnumValue("\u0412 \u043d\u0435\u0441\u044a\u0441\u0442\u043e\u044f\u0442\u0435\u043b\u043d\u043e\u0441\u0442 (\u043d\u0430 III \u0438\u043d\u0441\u0442\u0430\u043d\u0446\u0438\u044f)")
    В_НЕСЪСТОЯТЕЛНОСТ_НА_III_ИНСТАНЦИЯ("\u0412 \u043d\u0435\u0441\u044a\u0441\u0442\u043e\u044f\u0442\u0435\u043b\u043d\u043e\u0441\u0442 (\u043d\u0430 III \u0438\u043d\u0441\u0442\u0430\u043d\u0446\u0438\u044f)");
    private final String value;

    LiquidationOrInsolvency(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LiquidationOrInsolvency fromValue(String v) {
        for (LiquidationOrInsolvency c: LiquidationOrInsolvency.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
