//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.26 at 07:37:26 PM EEST 
//


package com.bulpros.integrations.regix.model.AV.TR.GetActualState;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NKIDType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NKIDType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="NKIDcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NKIDname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NKIDType", propOrder = {
    "nkiDcode",
    "nkiDname"
})
public class NKIDType {

    @XmlElement(name = "NKIDcode")
    protected String nkiDcode;
    @XmlElement(name = "NKIDname")
    protected String nkiDname;

    /**
     * Gets the value of the nkiDcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNKIDcode() {
        return nkiDcode;
    }

    /**
     * Sets the value of the nkiDcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNKIDcode(String value) {
        this.nkiDcode = value;
    }

    /**
     * Gets the value of the nkiDname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNKIDname() {
        return nkiDname;
    }

    /**
     * Sets the value of the nkiDname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNKIDname(String value) {
        this.nkiDname = value;
    }

}
