//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.26 at 07:37:26 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://egov.bg/RegiX/AV/TR", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.bulpros.integrations.regix.model.AV.TR.GetActualState;
