"""Add additional fields to mateus payments

Revision ID: 03938eea39ab
Revises: 70846e84e808
Create Date: 2024-01-27 13:51:56.580278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03938eea39ab'
down_revision = '70846e84e808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mateus_payment_request', sa.Column('amount', sa.Numeric(10, 2), nullable=True))
    op.add_column('mateus_payment_request', sa.Column('tax_period_year', sa.Integer(), nullable=True))
    op.add_column('mateus_payment_request', sa.Column('partida_no', sa.String(), nullable=True))
    op.add_column('mateus_payment_request', sa.Column('kind_debt_reg_id', sa.Integer(), nullable=True))
    op.add_column('mateus_payment_request', sa.Column('pay_order', sa.Integer(), nullable=True))
    op.add_column('mateus_payment_request', sa.Column('additional_data', sa.String(), nullable=True))

    op.execute("UPDATE mateus_payment_request SET amount=0, tax_period_year=1900, partida_no='000000', kind_debt_reg_id=0, pay_order=0,  additional_data=''")

    op.alter_column('mateus_payment_request', 'amount', nullable=False)
    op.alter_column('mateus_payment_request', 'tax_period_year', nullable=False)
    op.alter_column('mateus_payment_request', 'partida_no', nullable=False)
    op.alter_column('mateus_payment_request', 'kind_debt_reg_id', nullable=False)
    op.alter_column('mateus_payment_request', 'pay_order', nullable=False)
    op.alter_column('mateus_payment_request', 'additional_data', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mateus_payment_request', 'additional_data')
    op.drop_column('mateus_payment_request', 'kind_debt_reg_id')
    op.drop_column('mateus_payment_request', 'pay_order')
    op.drop_column('mateus_payment_request', 'partida_no')
    op.drop_column('mateus_payment_request', 'tax_period_year')
    op.drop_column('mateus_payment_request', 'amount')
    # ### end Alembic commands ###