"""regions_additional_data

Revision ID: 04d7aaa312cc
Revises: 25a31926b31b
Create Date: 2024-08-12 14:31:32.776406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04d7aaa312cc'
down_revision = '25a31926b31b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('region', sa.Column('ais_code', sa.String(), nullable=True))
    op.add_column('region', sa.Column('eik', sa.String(), nullable=True))
    op.add_column('region', sa.Column('id', sa.String(), nullable=True))
    op.add_column('region', sa.Column('title', sa.String(), nullable=True))
    op.add_column('region', sa.Column('client_id', sa.String(), nullable=True))
    op.add_column('region', sa.Column('secret_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('region', 'secret_key')
    op.drop_column('region', 'client_id')
    op.drop_column('region', 'title')
    op.drop_column('region', 'id')
    op.drop_column('region', 'eik')
    op.drop_column('region', 'ais_code')
    # ### end Alembic commands ###
