"""Add mateus payments

Revision ID: 06820df4b451
Revises: 795549c811d3
Create Date: 2024-01-23 12:44:23.431813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06820df4b451'
down_revision = '795549c811d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mateus_payment_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_identifier', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('tax_subject_id', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mateus_payment_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_identifier', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('payment_id', sa.String(), nullable=False),
    sa.Column('access_code', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['mateus_payment_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mateus_payment_request')
    op.drop_table('mateus_payment_group')
    # ### end Alembic commands ###
#