"""Add login events table

Revision ID: 09aefdd8723e
Revises: 2036e225bfc4
Create Date: 2025-01-13 15:37:32.700133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09aefdd8723e'
down_revision = '2036e225bfc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_identifier', sa.String(length=320), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=True),
    sa.Column('have_service', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('mateus_payment_group', 'is_notified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mateus_payment_group', 'is_notified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_table('login_events')
    # ### end Alembic commands ###
