"""Adding page blocks

Revision ID: 0c702462fc4e
Revises: 1a55b7674144
Create Date: 2023-02-28 14:00:37.601915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c702462fc4e'
down_revision = '1a55b7674144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_block',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_name', sa.String(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_name')
    )
    op.create_index(op.f('ix_form_history_parent_form_id'), 'form_history', ['parent_form_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_history_parent_form_id'), table_name='form_history')
    op.drop_table('page_block')
    # ### end Alembic commands ###
