"""Adding tenant_key to document transaction

Revision ID: 1d2324a18417
Revises: 8d3c275fc1df
Create Date: 2023-09-14 13:00:07.364085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d2324a18417'
down_revision = '8d3c275fc1df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_transaction', sa.Column('tenant_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_transaction', 'tenant_key')
    # ### end Alembic commands ###