"""Add user status transaction

Revision ID: 2036e225bfc4
Revises: b96e21c88505
Create Date: 2024-12-12 12:57:27.282397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2036e225bfc4'
down_revision = 'b96e21c88505'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_status_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_identifier', sa.String(length=320), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_status_transaction')
    # ### end Alembic commands ###
