from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '21464e45d1ee'
down_revision = '2a2088f520e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_request',
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('modified', sa.DateTime(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('payment_id', sa.String(), nullable=False),
                    sa.Column('application_id', sa.Integer(), nullable=False),
                    sa.Column('access_code', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_request')
    # ### end Alembic commands ###
