"""Making applicationId nullable for document transaction

Revision ID: 2a2088f520e6
Revises: 297ec3424c0b
Create Date: 2023-06-06 09:27:19.746995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a2088f520e6'
down_revision = '297ec3424c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_transaction', 'application_id',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_transaction', 'application_id',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    # ### end Alembic commands ###