"""chnage nullable flag for is_notified

Revision ID: 398ae7cc37ed
Revises: 87e4758400d3
Create Date: 2024-06-18 15:12:23.038900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '398ae7cc37ed'
down_revision = '87e4758400d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mateus_payment_group', sa.Column('is_notified', sa.Boolean(), nullable=True))
    op.add_column('mateus_payment_group', sa.Column('last_notification_try', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE mateus_payment_group SET is_notified = false")
    op.alter_column('mateus_payment_group', 'is_notified', nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mateus_payment_group', 'last_notification_try')
    op.drop_column('mateus_payment_group', 'is_notified')
    # ### end Alembic commands ###
