"""Changing column name for FAQ

Revision ID: 4869391d68dc
Revises: 7eb2c9eb0678
Create Date: 2023-03-21 10:35:12.725573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4869391d68dc'
down_revision = '7eb2c9eb0678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_block', sa.Column('attributes_translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('page_block', 'attributes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_block', sa.Column('attributes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('page_block', 'attributes_translations')
    # ### end Alembic commands ###