"""Add signature source to document transaction

Revision ID: 56c5877774bc
Revises: 7ca6bfc5df75
Create Date: 2024-02-21 14:59:39.514496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56c5877774bc'
down_revision = '7ca6bfc5df75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_transaction', sa.Column('signature_source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_transaction', 'signature_source')
    # ### end Alembic commands ###