"""Adding machine name to form mapper

Revision ID: 5b7bcdbf9673
Revises: 4869391d68dc
Create Date: 2023-04-06 14:04:31.836774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b7bcdbf9673'
down_revision = '4869391d68dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_process_mapper', sa.Column('machine_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_process_mapper', 'machine_name')
    # ### end Alembic commands ###