"""Adding document status as an object

Revision ID: 5ee3bb9a4b4d
Revises: b3c5007a4e29
Create Date: 2023-05-03 13:48:01.169846

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ee3bb9a4b4d'
down_revision = 'b3c5007a4e29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_status',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('eurotrust_status', sa.Integer(), nullable=True),
    sa.Column('formio_status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('document_transaction', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_transaction', sa.Column('status', postgresql.ENUM('PENDING', 'SIGNED', 'REJECTED', 'EXPIRED', 'FAILED', 'WITHDRAWN', 'UNDELIVERABLE', 'ON_HOLD', name='signingstatus'), autoincrement=False, nullable=True))
    op.drop_table('document_status')
    # ### end Alembic commands ###