"""Adding page param to page blocks

Revision ID: 642bc207083d
Revises: 0c702462fc4e
Create Date: 2023-03-10 10:36:53.707892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642bc207083d'
down_revision = '0c702462fc4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_block', sa.Column('page', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_block', 'page')
    # ### end Alembic commands ###
