"""Changing machine_name to form_path for FormProcessMapper

Revision ID: 6dcfb1514448
Revises: 5b7bcdbf9673
Create Date: 2023-04-11 13:33:38.926450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dcfb1514448'
down_revision = '5b7bcdbf9673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_process_mapper', sa.Column('form_path', sa.String(length=100), nullable=True))
    op.drop_column('form_process_mapper', 'machine_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_process_mapper', sa.Column('machine_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('form_process_mapper', 'form_path')
    # ### end Alembic commands ###