"""Add ref number to mateus requests

Revision ID: 7ae6387645b5
Revises: 3d7f3f4980c6
Create Date: 2024-01-31 08:37:40.279509

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7ae6387645b5'
down_revision = '3d7f3f4980c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mateus_payment_request', sa.Column('payment_request_id', sa.String(), nullable=True))
    op.execute('UPDATE mateus_payment_request SET payment_request_id=mateus_payment_request.payment_id')
    op.alter_column('mateus_payment_request', 'payment_request_id', nullable=False)
    op.create_unique_constraint(None, 'mateus_payment_request', ['payment_request_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mateus_payment_request', type_='unique')
    op.drop_column('mateus_payment_request', 'payment_request_id')
    # ### end Alembic commands ###
