"""Add more additional fields to mateus requests

Revision ID: 7ca6bfc5df75
Revises: de812ca73ee4
Create Date: 2024-02-13 09:06:27.914886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca6bfc5df75'
down_revision = 'de812ca73ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mateus_payment_request', sa.Column('rnu', sa.String(), nullable=True))
    op.add_column('mateus_payment_request', sa.Column('municipality_id', sa.Integer(), nullable=True))
    op.add_column('mateus_payment_request', sa.Column('debt_instalment_id', sa.Integer(), nullable=True))
    op.add_column('mateus_payment_request', sa.Column('residual', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('mateus_payment_request', sa.Column('interest', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mateus_payment_request', 'interest')
    op.drop_column('mateus_payment_request', 'residual')
    op.drop_column('mateus_payment_request', 'debt_instalment_id')
    op.drop_column('mateus_payment_request', 'municipality_id')
    op.drop_column('mateus_payment_request', 'rnu')
    # ### end Alembic commands ###