"""Adding faq

Revision ID: 7eb2c9eb0678
Revises: 642bc207083d
Create Date: 2023-03-20 13:22:24.843545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7eb2c9eb0678'
down_revision = '642bc207083d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FAQ',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_favoured', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FAQ')
    # ### end Alembic commands ###