"""add e payment id column in mateus payment group table

Revision ID: 87e4758400d3
Revises: 9b408a6c59e5
Create Date: 2024-06-13 13:52:13.483733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e4758400d3'
down_revision = '9b408a6c59e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mateus_payment_group', sa.Column('e_payment_payment_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mateus_payment_group', 'e_payment_payment_id')
    # ### end Alembic commands ###
