"""remove personal identifier from mateus_payment_request_table

Revision ID: 9b408a6c59e5
Revises: ebd66567ec04
Create Date: 2024-06-11 11:16:22.150846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b408a6c59e5'
down_revision = 'ebd66567ec04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mateus_payment_request', 'person_identifier')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mateus_payment_request', sa.Column('person_identifier', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
