"""Added_retry_count_column

Revision ID: 9f6bb1a43df2
Revises: 5998394ef4af
Create Date: 2024-06-24 09:26:57.210297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f6bb1a43df2'
down_revision = '5998394ef4af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mateus_payment_group', sa.Column('retry_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE mateus_payment_group SET retry_count = 0")
    op.alter_column('mateus_payment_group', 'retry_count', nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mateus_payment_group', 'retry_count')
    # ### end Alembic commands ###
