"""Adding document transactions

Revision ID: b3c5007a4e29
Revises: 6dcfb1514448
Create Date: 2023-04-28 10:03:26.425249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c5007a4e29'
down_revision = '6dcfb1514448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_transaction',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=12), nullable=False),
    sa.Column('thread_id', sa.String(length=12), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SIGNED', 'REJECTED', 'EXPIRED', 'FAILED', 'WITHDRAWN', 'UNDELIVERABLE', 'ON_HOLD', name='signingstatus'), nullable=True),
    sa.Column('application_id', sa.String(length=12), nullable=False),
    sa.Column('formio_id', sa.String(length=24), nullable=False),
    sa.Column('user_email', sa.String(length=320), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_transaction')
    # ### end Alembic commands ###