"""Add statuses for receipts

Revision ID: b96e21c88505
Revises: 04d7aaa312cc
Create Date: 2024-11-13 08:07:12.964192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b96e21c88505'
down_revision = '04d7aaa312cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Adding statuses for receipts from SM-1627. For more info take a look of the comments!
    op.execute("""\
        INSERT INTO document_status (
            created,
            modified,
            title,
            eurotrust_status,
            formio_status
        ) VALUES (
            NOW(),
            NOW(),
            'Delivering',
            8,
            'delivering'        
        ),
        (
            NOW(),
            NOW(),
            'Generating',
            9,
            'generating'        
        ),
        (
            NOW(),
            NOW(),
            'Generated',
            10,
            'generated'        
        ),
        (
            NOW(),
            NOW(),
            'Processing',
            11,
            'processing'        
        );
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DELETE FROM document_status
        WHERE eurotrust_status IN (8, 9, 10, 11);
    """)
    # ### end Alembic commands ###
