"""Updating application models

Revision ID: cd34aee6015a
Revises: 2a2088f520e6
Create Date: 2023-09-11 10:38:17.237521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cd34aee6015a'
down_revision = '2a2088f520e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title_translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('content_translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('is_favoured', sa.Boolean(), nullable=True),
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('FAQ')
    op.add_column('application', sa.Column('is_resubmit', sa.Boolean(), nullable=True))
    op.add_column('application', sa.Column('event_name', sa.String(length=100), nullable=True))
    op.add_column('application_audit', sa.Column('color', sa.String(length=50), nullable=True))
    op.add_column('application_audit', sa.Column('percentage', sa.Double(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_audit', 'percentage')
    op.drop_column('application_audit', 'color')
    op.drop_column('application', 'event_name')
    op.drop_column('application', 'is_resubmit')
    op.create_table('FAQ',
        sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"FAQ_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
        sa.Column('title_translations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column('content_translations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column('is_favoured', sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='FAQ_pkey')
    )
    op.drop_table('faq')
    # ### end Alembic commands ###