"""Change mateus payments table structure by new requirements

Revision ID: ebd66567ec04
Revises: 56c5877774bc
Create Date: 2024-06-11 06:35:13.455184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebd66567ec04'
down_revision = '56c5877774bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mateus_payment_group', sa.Column('payment_id', sa.String(), nullable=True))
    op.add_column('mateus_payment_group', sa.Column('access_code', sa.String(), nullable=True))
    op.drop_constraint('mateus_payment_request_payment_id_key', 'mateus_payment_request', type_='unique')
    op.drop_constraint('mateus_payment_request_payment_request_id_key', 'mateus_payment_request', type_='unique')
    op.drop_column('mateus_payment_request', 'access_code')
    op.drop_column('mateus_payment_request', 'payment_id')
    op.drop_column('mateus_payment_request', 'status')
    op.drop_column('mateus_payment_request', 'payment_request_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mateus_payment_request', sa.Column('payment_request_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('mateus_payment_request', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mateus_payment_request', sa.Column('payment_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('mateus_payment_request', sa.Column('access_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('mateus_payment_request_payment_request_id_key', 'mateus_payment_request', ['payment_request_id'])
    op.create_unique_constraint('mateus_payment_request_payment_id_key', 'mateus_payment_request', ['payment_id'])
    op.drop_column('mateus_payment_group', 'access_code')
    op.drop_column('mateus_payment_group', 'payment_id')
    # ### end Alembic commands ###
