"""Creating identity request model

Revision ID: f1c985231b00
Revises: 8309632b2ed3
Create Date: 2023-10-16 08:42:59.130020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1c985231b00'
down_revision = '8309632b2ed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_request',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('transaction_id', sa.String(length=12), nullable=False),
        sa.Column('thread_id', sa.String(length=12), nullable=False),
        sa.Column('tenant_key', sa.String(), nullable=True),
        sa.Column('person_identifier', sa.String(length=16), nullable=False),
        sa.Column('valid_untill', sa.DateTime(), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('identity_request')
    # ### end Alembic commands ###