pipeline {
    environment {
        DEPLOY = "${env.BRANCH_NAME == "develop" ? "true" : "false"}"
        NAME = "${env.BRANCH_NAME == "develop" ? "example" : "example-staging"}"

    }
  
    agent {
      kubernetes {
        yaml '''
          apiVersion: v1
          kind: Pod
          spec:
            containers:
            - name: micro
              image: docker.io/ubuntu:latest
              volumeMounts:
                - name: js
                  mountPath: /mnt
              command:
              - cat
              tty: true
            volumes:
            - name: js
              nfs:
                server: 192.168.201.46
                path: /mnt
          '''
      }
    }

    stages {
      stage('WEB Micro FrontEnd NAV') {
          steps {
            container('micro'){                
                sh '''
                apt update
                apt-get install -y  curl
                curl -sL https://deb.nodesource.com/setup_14.x |  bash -
                apt-get install -y  nodejs 
                node -v
                npm install
                npm run build
                ls -l
                rm -rf /mnt/forms-flow-web-mf-nav/*
                mv ./dist /mnt/forms-flow-web-mf-nav
                '''              
            }
          }
        }
  }
}