//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.26 at 07:37:25 PM EEST 
//


package com.bulpros.integrations.regix.model.GRAO.RelationsSearch;

import com.bulpros.integrations.regix.model.GRAO.PersonDataSearch.PersonRelationType;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for RelationsResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RelationsResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PersonRelations" type="{http://egov.bg/RegiX/GRAO/NBD}PersonRelationType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelationsResponseType", namespace = "http://egov.bg/RegiX/GRAO/NBD/RelationsResponse", propOrder = {
    "personRelations"
})
@XmlRootElement(name = "RelationsResponse", namespace = "http://egov.bg/RegiX/GRAO/NBD/RelationsResponse")
public class RelationsResponseType {

    @XmlElement(name = "PersonRelations")
    protected List<PersonRelationType> personRelations;

    /**
     * Gets the value of the personRelations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personRelations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonRelations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonRelationType }
     * 
     * 
     */
    public List<PersonRelationType> getPersonRelations() {
        if (personRelations == null) {
            personRelations = new ArrayList<PersonRelationType>();
        }
        return this.personRelations;
    }

}
