//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.26 at 07:37:26 PM EEST 
//


package com.bulpros.integrations.regix.model.AZ.GetJobSeekerStatus;

import javax.xml.bind.annotation.*;


/**
 * Входни параметри на справка по ЕГН/ЛНЧ за статус на търсещо работа лице
 * 
 * <p>Java class for JobSeekerStatusRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JobSeekerStatusRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PersonalID" type="{http://egov.bg/RegiX/AZ}PersonalID"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JobSeekerStatusRequestType", namespace = "http://egov.bg/RegiX/AZ/JobSeekerStatusRequest", propOrder = {
    "personalID"
})
@XmlRootElement(name = "JobSeekerStatusRequest", namespace = "http://egov.bg/RegiX/AZ/JobSeekerStatusRequest")
public class JobSeekerStatusRequestType {

    @XmlElement(name = "PersonalID", required = true)
    protected String personalID;

    /**
     * Gets the value of the personalID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalID() {
        return personalID;
    }

    /**
     * Sets the value of the personalID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalID(String value) {
        this.personalID = value;
    }

}
