platform :ios, '15.0'
use_frameworks!

target 'Digital Sofia' do
    pod "AFNetworking", "4.0.1"
    pod 'DocumentReader', '7.4.3826'
    pod 'DocumentReaderMRZRFID', '7.4.9825'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'Firebase/Crashlytics'

project 'Digital Sofia', 'Release-Dev' => :release, 'Debug-Dev' => :debug
end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
   config.build_settings['ENABLE_BITCODE'] = 'NO'
   xcconfig_path = config.base_configuration_reference.real_path
   xcconfig = File.read(xcconfig_path)
   xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
   File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
  end
 end
end
