 platform :ios, '15.0'

target 'Digital Sofia' do
  use_frameworks!

    pod 'Alamofire'
    pod "AFNetworking", "4.0.1"
    pod 'DocumentReader', '6.3.2494'
    pod 'DocumentReaderMRZRFID', '6.3.6217'

# Add the pods for the Firebase products you want to use in your app
# For example, to use Firebase Authentication and Cloud Firestore
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'

end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
   xcconfig_path = config.base_configuration_reference.real_path
   xcconfig = File.read(xcconfig_path)
   xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
   File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
  end
 end
end
