import { APPLICATION_STATUS } from "../../../constants/formEmbeddedConstants";

const getMockItems = (applicationStatus) => {
  switch (applicationStatus) {
    case APPLICATION_STATUS.DRAFT_IN_PROGRESS:
      return [
        {
          applicationId: 3232,
          path: "sofia-changeofpernamentaddress-1684342756405",
          status: "Draft",
          formioName: "Смяна на постоянен адрес",
          formioSubmissionId: null,
          formioFormId: "650156a2b7a5d5df1fdf371d",
          processInstanceId: null,
          camundaProcessKey: "Process_sofiade",
          created: "2023-11-01T07:20:29.679652",
          modified: "2023-11-01T07:20:29.679658",
          draftId: 3080,
          formioData: {
            behalf: "myBehalf",
            applicationStatus: "draftInProgress",
            personDataStepTitle: "Данни на живущия",
            applicationId: "",
            personIdentifier: "PNOBG-0000000000",
            email: "test@test.com",
            idCardStatus: "ВАЛИДЕН",
            is_pdf: false,
            idCardNumber: "123456789",
            autoFillData: true,
            firstName: "test.firstName",
            middleName: "test.middleName",
            lastName: "test.lastName",
            idCardCreationDate: "21.08.2018",
            idCardExpiryDate: "21.08.2028",
            idCardIssiuedBy: "МВР/MoI BGR",
            property: "",
            document: [],
            propertyOwnerFirstName: "",
            propertyOwnerLastName: "",
            propertyOwnerEmail: "",
            propertyOwnerPhone: "",
            fullAddress: "test.fullAddress",
            streetNumberValue: "",
            regionValue: "",
            address: {},
            streetNumber: {},
            entrance: "",
            floorNumber: "",
            appartmentNumber: "",
            region: {},
            reference_number: "",
            pdfData: "",
            pdfUrl: "",
            addressChangeType: "permanent",
          },
          camundaData: null,
        },
      ];
    case APPLICATION_STATUS.FORM_SUBMITTED:
      return [
        {
          applicationId: 3233,
          path: "sofia-changeofpernamentaddress-1684342756405",
          status: "formSubmitted",
          formioName: "Смяна на постоянен адрес",
          formioSubmissionId: "6542004fbb482c546477aa63",
          formioFormId: "650156a2b7a5d5df1fdf371d",
          processInstanceId: "90374d63-7889-11ee-8add-2a60bee8aa7b",
          camundaProcessKey: "Process_sofiade",
          created: "2023-11-01T07:36:58.651443",
          modified: "2023-11-01T07:38:06.609214",
          draftId: null,
          formioData: {
            applicationId: "3233",
            applicationStatus: "formSubmitted",
            personIdentifier: "PNOBG-0000000",
            phone: "",
            behalf: "myBehalf",
            personDataStepTitle: "Данни на живущия",
            email: "test@test.com",
            idCardStatus: "ВАЛИДЕН",
            is_pdf: false,
            idCardNumber: "123456789",
            autoFillData: true,
            firstName: "test.firstName",
            middleName: "test.middleName",
            lastName: "test.lastName",
            idCardCreationDate: "21.08.2018",
            idCardExpiryDate: "21.08.2028",
            idCardIssiuedBy: "МВР/MoI BGR",
            property: "myOwnProperty",
            document: [],
            propertyOwnerFirstName: "",
            propertyOwnerLastName: "",
            propertyOwnerEmail: "",
            propertyOwnerPhone: "",
            fullAddress: "test.fullAddress",
            streetNumberValue: "001",
            regionValue: "Средец",
            address: {
              name_pa: "**.3-ТА",
              region_id: 1,
              region_name: "Средец",
            },
            streetNumber: {
              building_number: "001",
              region_id: 1,
            },
            entrance: "",
            floorNumber: "",
            appartmentNumber: "",
            region: {
              code: "68134-01",
              city_are_code: 1,
              name: "Средец",
              modified: "2023-05-18 08:49:23.513895",
              created: "2023-05-18 08:49:23.513891",
              reference_number_code: "РСЦ",
            },
            reference_number: "test.referenceNumber",
            pdfUrl:
              "http://digital-api.digitalsofia.digital/form/sofia-generated-files/submission?data.applicationId=3233&userId=PNOBG-00000000",
            propertyOwnerPdfUrl: "",
            propertyOwnerSignutureDate: "",
            propertyOwnerRejectionDate: "",
            propertyOwnerInvitationExpiredDate: "",
            propertyOwnerInvitationWithdrawnDate: "",
            trusteePdfUrl: "",
            trusteeSignutureDate: "",
            trusteeRejectionDate: "",
            trusteeInvitationExpiredDate: "",
            trusteeInvitationWithdrawnDate: "",
            submitterTaskId: "",
            documentFormioId: "6542003fbb482c546477aa22",
            isPdfLoading: false,
            addressChangeType: "permanent",
          },
        },
      ];
    case APPLICATION_STATUS.WAITING_FOR_THIRD_PARTY_SIGNUTURE:
      return [
        {
          applicationId: 3234,
          path: "sofia-changeofpernamentaddress-1684342756405",
          status: "waitingForThirdPartySigniture",
          formioName: "Смяна на постоянен адрес",
          formioSubmissionId: "654203a7bb482c546477ac63",
          formioFormId: "650156a2b7a5d5df1fdf371d",
          processInstanceId: "8e83e665-788b-11ee-8add-2a60bee8aa7b",
          camundaProcessKey: "Process_sofiade",
          created: "2023-11-01T07:51:25.231829",
          modified: "2023-11-01T07:52:13.321381",
          draftId: null,
          formioData: {
            applicationId: "3234",
            applicationStatus: "waitingForThirdPartySigniture",
            personIdentifier: "PNOBG-00000000",
            phone: "",
            behalf: "myBehalf",
            personDataStepTitle: "Данни на живущия",
            email: "test@test.com",
            idCardStatus: "ВАЛИДЕН",
            is_pdf: false,
            idCardNumber: "123456789",
            autoFillData: true,
            firstName: "test.firstName",
            middleName: "test.middleName",
            lastName: "test.lastName",
            idCardCreationDate: "21.08.2018",
            idCardExpiryDate: "21.08.2028",
            idCardIssiuedBy: "МВР/MoI BGR",
            property: "anotherPersonProperty",
            document: [],
            propertyOwnerFirstName: "test.ownerFirstName",
            propertyOwnerLastName: "test.ownerLastName",
            propertyOwnerEmail: "test@test.com",
            propertyOwnerPhone: "+11111111",
            fullAddress: "**.3-ТА, № 001, София, Средец",
            streetNumberValue: "001",
            regionValue: "Средец",
            address: {
              name_pa: "**.3-ТА",
              region_id: 1,
              region_name: "Средец",
            },
            streetNumber: {
              building_number: "001",
              region_id: 1,
            },
            entrance: "",
            floorNumber: "",
            appartmentNumber: "",
            region: {
              code: "68134-01",
              city_are_code: 1,
              name: "Средец",
              modified: "2023-05-18 08:49:23.513895",
              created: "2023-05-18 08:49:23.513891",
              reference_number_code: "РСЦ",
            },
            reference_number: "test.referenceNumber",
            pdfUrl:
              "http://digital-api.digitalsofia.digital/form/sofia-generated-files/submission?data.applicationId=3234&userId=PNOBG-00000000",
            propertyOwnerPdfUrl: "",
            propertyOwnerSignutureDate: "",
            propertyOwnerRejectionDate: "",
            propertyOwnerInvitationExpiredDate: "",
            propertyOwnerInvitationWithdrawnDate: "",
            trusteePdfUrl: "",
            trusteeSignutureDate: "",
            trusteeRejectionDate: "",
            trusteeInvitationExpiredDate: "",
            trusteeInvitationWithdrawnDate: "",
            submitterTaskId: "",
            documentFormioId: "654203a4bb482c546477ac42",
            isPdfLoading: false,
            addressChangeType: "permanent",
          },
        },
      ];
    case APPLICATION_STATUS.EXPIRED_INVITATION:
      return [
        {
          applicationId: 200,
          path: "sofia-changeofpernamentaddress",
          status: "expiredInvitation",
          formioName: "Смяна на постоянен адрес",
          formioSubmissionId: "65291a5d2860fe831d434aa8",
          formioFormId: "651d58812860fe831d4010c5",
          processInstanceId: "653f3461-69b2-11ee-9d4e-0e2be9820e7a",
          camundaProcessKey: "Process_sofiade",
          created: "2023-10-13T10:21:57.775350",
          modified: "2023-10-13T10:24:55.935882",
          draftId: null,
          formioData: {
            applicationId: "200",
            applicationStatus: "expiredInvitation",
            personIdentifier: "PNOBG-00000000",
            phone: "+3591111111",
            behalf: "myBehalf",
            personDataStepTitle: "Resident data",
            email: "test@test.com",
            idCardStatus: "ВАЛИДЕН",
            is_pdf: false,
            draftId: false,
            idCardNumber: "123456789",
            autoFillData: true,
            firstName: "test.firstName",
            middleName: "test.middleName",
            lastName: "test.lastName",
            idCardCreationDate: "21.08.2018",
            idCardExpiryDate: "21.08.2028",
            idCardIssiuedBy: "МВР/MoI BGR",
            property: "anotherPersonProperty",
            document: [],
            propertyOwnerFirstName: "test.ownerFirstName",
            propertyOwnerLastName: "test.ownerLastName",
            propertyOwnerEmail: "test@test.com",
            propertyOwnerPhone: "+3591111111",
            fullAddress: "**.3-ТА, № 001, София, Средец",
            streetNumberValue: "001",
            regionValue: "Средец",
            address: {
              region_name: "Средец",
              region_id: 1,
              name_pa: "**.3-ТА",
            },
            streetNumber: {
              building_number: "001",
              region_id: 1,
            },
            entrance: "",
            floorNumber: "",
            appartmentNumber: "",
            region: {
              code: "68134-01",
              modified: "2023-05-18 08:49:23.513895",
              name: "Средец",
              city_are_code: 1,
              created: "2023-05-18 08:49:23.513891",
              reference_number_code: "РСЦ",
            },
            reference_number: "test.referenceNumber",
            pdfUrl:
              "http://api-test-eservices.egov.bg/form/sofia-generated-files/submission?data.applicationId=200&userId=PNOBG-0000000",
            propertyOwnerPdfUrl: "",
            propertyOwnerSignutureDate: "",
            propertyOwnerRejectionDate: "",
            propertyOwnerInvitationExpiredDate:
              "Mon Oct 23 2023 10:32:08 GMT+0000 (GMT)",
            propertyOwnerInvitationWithdrawnDate: "",
            trusteePdfUrl: "",
            trusteeSignutureDate: "",
            trusteeRejectionDate: "",
            trusteeInvitationExpiredDate: "",
            trusteeInvitationWithdrawnDate: "",
            submitterTaskId: "",
            documentFormioId: "65291a5b2860fe831d434a87",
            isPdfLoading: false,
            addressChangeType: "permanent",
          },
        },
      ];
    case APPLICATION_STATUS.CANCELLED_THIRD_PARTY_SIGNUTURE:
      return [
        {
          applicationId: 24,
          path: "sofia-changeofpernamentaddress",
          status: "cancelledThirdPartySigniture",
          formioName: "Смяна на постоянен адрес",
          formioSubmissionId: "65421cb22fe2d7d686a48c09",
          formioFormId: "6530dca38ceb5b25403a78d0",
          processInstanceId: "7b40b95c-789a-11ee-bcb4-96b0a6073479",
          camundaProcessKey: "Process_sofiade",
          created: "2023-11-01T09:38:28.053018",
          modified: "2023-11-01T09:40:58.805247",
          draftId: null,
          formioData: {
            applicationId: "24",
            applicationStatus: "cancelledThirdPartySigniture",
            personIdentifier: "PNOBG-00000000",
            phone: "",
            behalf: "",
            personDataStepTitle: "Resident data",
            email: "test@test.com",
            idCardStatus: "ВАЛИДЕН",
            is_pdf: false,
            draftId: 17,
            idCardNumber: "123456789",
            autoFillData: true,
            firstName: "test.firstName",
            middleName: "test.middleName",
            lastName: "test.lastName",
            idCardCreationDate: "21.08.2018",
            idCardExpiryDate: "21.08.2028",
            idCardIssiuedBy: "МВР/MoI BGR",
            property: "anotherPersonProperty",
            document: [],
            propertyOwnerFirstName: "test.ownerFirstName",
            propertyOwnerLastName: "test.ownerLastName",
            propertyOwnerEmail: "test@test.com",
            propertyOwnerPhone: "+1111111",
            fullAddress: "**.3-ТА, № 001, София, Средец",
            streetNumberValue: "001",
            regionValue: "Средец",
            address: {
              region_id: 1,
              region_name: "Средец",
              name_pa: "**.3-ТА",
            },
            streetNumber: {
              building_number: "001",
              region_id: 1,
            },
            entrance: "",
            floorNumber: "",
            appartmentNumber: "",
            region: {
              code: "68134-01",
              city_are_code: 1,
              name: "Средец",
              modified: "2023-05-18 08:49:23.513895",
              created: "2023-05-18 08:49:23.513891",
              reference_number_code: "РСЦ",
            },
            reference_number: "test.referenceNumber",
            pdfUrl:
              "http://api-dev-eservices.egov.bg/form/sofia-generated-files/submission?data.applicationId=24&userId=PNOBG-0000000",
            propertyOwnerPdfUrl: "",
            propertyOwnerSignutureDate: "",
            propertyOwnerRejectionDate:
              "Wed Nov 01 2023 09:40:58 GMT+0000 (GMT)",
            propertyOwnerInvitationExpiredDate: "",
            propertyOwnerInvitationWithdrawnDate: "",
            trusteePdfUrl: "",
            trusteeSignutureDate: "",
            trusteeRejectionDate: "",
            trusteeInvitationExpiredDate: "",
            trusteeInvitationWithdrawnDate: "",
            submitterTaskId: "",
            documentFormioId: "65421cad2fe2d7d686a48be8",
            isPdfLoading: false,
            addressChangeType: "permanent",
          },
        },
      ];
    case APPLICATION_STATUS.SIGNITURE_NEEDED:
      return [
        {
          applicationId: 24,
          path: "sofia-changeofpernamentaddress",
          status: "signitureNeeded",
          formioName: "Смяна на постоянен адрес",
          formioSubmissionId: "65421cb22fe2d7d686a48c09",
          formioFormId: "6530dca38ceb5b25403a78d0",
          processInstanceId: "7b40b95c-789a-11ee-bcb4-96b0a6073479",
          camundaProcessKey: "Process_sofiade",
          created: "2023-11-01T09:38:28.053018",
          modified: "2023-11-01T11:24:39.194220",
          draftId: null,
          formioData: {
            applicationId: "24",
            applicationStatus: "signitureNeeded",
            personIdentifier: "PNOBG-0000000000",
            phone: "",
            behalf: "myBehalf",
            personDataStepTitle: "Resident data",
            email: "test@test.com",
            idCardStatus: "ВАЛИДЕН",
            is_pdf: false,
            draftId: 17,
            idCardNumber: "123456789",
            autoFillData: true,
            firstName: "test.firstName",
            middleName: "test.middleName",
            lastName: "test.lastName",
            idCardCreationDate: "21.08.2018",
            idCardExpiryDate: "21.08.2028",
            idCardIssiuedBy: "МВР/MoI BGR",
            property: "anotherPersonProperty",
            document: [],
            propertyOwnerFirstName: "test.ownerFirstName",
            propertyOwnerLastName: "test.ownerLastName",
            propertyOwnerEmail: "test@test.com",
            propertyOwnerPhone: "+359889228197",
            fullAddress: "**.3-ТА, № 001, София, Средец",
            streetNumberValue: "001",
            regionValue: "Средец",
            address: {
              region_id: 1,
              region_name: "Средец",
              name_pa: "**.3-ТА",
            },
            streetNumber: {
              building_number: "001",
              region_id: 1,
            },
            entrance: "",
            floorNumber: "",
            appartmentNumber: "",
            region: {
              code: "68134-01",
              city_are_code: 1,
              name: "Средец",
              modified: "2023-05-18 08:49:23.513895",
              created: "2023-05-18 08:49:23.513891",
              reference_number_code: "РСЦ",
            },
            reference_number: "test.referenceNumber",
            pdfUrl:
              "http://api-dev-eservices.egov.bg/form/sofia-generated-files/submission?data.applicationId=24&userId=PNOBG-0000000000",
            propertyOwnerPdfUrl:
              "http://api-dev-eservices.egov.bg/form/sofia-generated-files/submission?data.applicationId=27&userId=PNOBG-0000000000",
            propertyOwnerSignutureDate:
              "Wed Nov 01 2023 11:24:36 GMT+0000 (GMT)",
            propertyOwnerRejectionDate: "",
            propertyOwnerInvitationExpiredDate: "",
            propertyOwnerInvitationWithdrawnDate: "",
            trusteePdfUrl: "",
            trusteeSignutureDate: "",
            trusteeRejectionDate: "",
            trusteeInvitationExpiredDate: "",
            trusteeInvitationWithdrawnDate: "",
            submitterTaskId: "3ef84c82-78a9-11ee-bcb4-96b0a6073479",
            documentFormioId: "65421cad2fe2d7d686a48be8",
            isPdfLoading: false,
            addressChangeType: "permanent",
          },
        },
      ];
    case APPLICATION_STATUS.WITHDRAWN_INVITATION:
      return [
        {
          applicationId: 24,
          path: "sofia-changeofpernamentaddress",
          status: "withdrawn",
          formioName: "Смяна на постоянен адрес",
          formioSubmissionId: "65421cb22fe2d7d686a48c09",
          formioFormId: "6530dca38ceb5b25403a78d0",
          processInstanceId: "7b40b95c-789a-11ee-bcb4-96b0a6073479",
          camundaProcessKey: "Process_sofiade",
          created: "2023-11-01T09:38:28.053018",
          modified: "2023-11-01T09:40:58.805247",
          draftId: null,
          formioData: {
            applicationId: "24",
            applicationStatus: "withdrawn",
            personIdentifier: "PNOBG-00000000",
            phone: "",
            behalf: "myBehalf",
            personDataStepTitle: "Resident data",
            email: "test@test.com",
            idCardStatus: "ВАЛИДЕН",
            is_pdf: false,
            draftId: 17,
            idCardNumber: "123456789",
            autoFillData: true,
            firstName: "test.firstName",
            middleName: "test.middleName",
            lastName: "test.lastName",
            idCardCreationDate: "21.08.2018",
            idCardExpiryDate: "21.08.2028",
            idCardIssiuedBy: "МВР/MoI BGR",
            property: "anotherPersonProperty",
            document: [],
            propertyOwnerFirstName: "test.ownerFirstName",
            propertyOwnerLastName: "test.ownerLastName",
            propertyOwnerEmail: "test@test.com",
            propertyOwnerPhone: "+1111111",
            fullAddress: "**.3-ТА, № 001, София, Средец",
            streetNumberValue: "001",
            regionValue: "Средец",
            address: {
              region_id: 1,
              region_name: "Средец",
              name_pa: "**.3-ТА",
            },
            streetNumber: {
              building_number: "001",
              region_id: 1,
            },
            entrance: "",
            floorNumber: "",
            appartmentNumber: "",
            region: {
              code: "68134-01",
              city_are_code: 1,
              name: "Средец",
              modified: "2023-05-18 08:49:23.513895",
              created: "2023-05-18 08:49:23.513891",
              reference_number_code: "РСЦ",
            },
            reference_number: "test.referenceNumber",
            pdfUrl:
              "http://api-dev-eservices.egov.bg/form/sofia-generated-files/submission?data.applicationId=24&userId=PNOBG-0000000",
            propertyOwnerPdfUrl: "",
            propertyOwnerSignutureDate: "",
            propertyOwnerRejectionDate: "",
            propertyOwnerInvitationExpiredDate: "",
            propertyOwnerInvitationWithdrawnDate:
              "Wed Nov 01 2023 09:40:58 GMT+0000 (GMT)",
            trusteePdfUrl: "",
            trusteeSignutureDate: "",
            trusteeRejectionDate: "",
            trusteeInvitationExpiredDate: "",
            trusteeInvitationWithdrawnDate: "",
            submitterTaskId: "",
            documentFormioId: "65421cad2fe2d7d686a48be8",
            isPdfLoading: false,
            addressChangeType: "permanent",
          },
        },
      ];
    case APPLICATION_STATUS.SIGN_DOCUMENT_PENDING:
      return [
        {
          applicationId: 28,
          path: "sofia-changeofpernamentaddress",
          status: "signDocumentPending",
          formioName: "Смяна на постоянен адрес",
          formioSubmissionId: "654239572fe2d7d686a4b5ce",
          formioFormId: "6530dca38ceb5b25403a78d0",
          processInstanceId: "8e4aee43-78ab-11ee-bcb4-96b0a6073479",
          camundaProcessKey: "Process_sofiade",
          created: "2023-11-01T11:40:22.845392",
          modified: "2023-11-01T11:41:12.334737",
          draftId: null,
          formioData: {
            applicationId: "28",
            applicationStatus: "signDocumentPending",
            personIdentifier: "PNOBG-00000000",
            phone: "",
            behalf: "myBehalf",
            personDataStepTitle: "Resident data",
            email: "test@test.com",
            idCardStatus: "ВАЛИДЕН",
            is_pdf: false,
            draftId: 21,
            idCardNumber: "123456789",
            autoFillData: true,
            firstName: "test.firstName",
            middleName: "test.middleName",
            lastName: "test.lastName",
            idCardCreationDate: "21.08.2018",
            idCardExpiryDate: "21.08.2028",
            idCardIssiuedBy: "МВР/MoI BGR",
            property: "myOwnProperty",
            document: [],
            propertyOwnerFirstName: "",
            propertyOwnerLastName: "",
            propertyOwnerEmail: "",
            propertyOwnerPhone: "",
            fullAddress: "**.3-ТА, № 001, София, Средец",
            streetNumberValue: "001",
            regionValue: "Средец",
            address: {
              region_id: 1,
              region_name: "Средец",
              name_pa: "**.3-ТА",
            },
            streetNumber: {
              building_number: "001",
              region_id: 1,
            },
            entrance: "",
            floorNumber: "",
            appartmentNumber: "",
            region: {
              reference_number_code: "РСЦ",
              code: "68134-01",
              city_are_code: 1,
              modified: "2023-05-18 08:49:23.513895",
              name: "Средец",
              created: "2023-05-18 08:49:23.513891",
            },
            reference_number: "test.referenceNumber",
            pdfUrl:
              "http://api-dev-eservices.egov.bg/form/sofia-generated-files/submission?data.applicationId=28&userId=PNOBG-0000000",
            propertyOwnerPdfUrl: "",
            propertyOwnerSignutureDate: "",
            propertyOwnerRejectionDate: "",
            propertyOwnerInvitationExpiredDate: "",
            propertyOwnerInvitationWithdrawnDate: "",
            trusteePdfUrl: "",
            trusteeSignutureDate: "",
            trusteeRejectionDate: "",
            trusteeInvitationExpiredDate: "",
            trusteeInvitationWithdrawnDate: "",
            submitterTaskId: "",
            documentFormioId: "654239452fe2d7d686a4b57d",
            isPdfLoading: false,
            addressChangeType: "permanent",
          },
        },
      ];
    default:
      return [];
  }
};

export const mockServices = (applicationStatus) => {
  return {
    fetch: () => ({}),
    data: {
      items: getMockItems(applicationStatus),
      total: 1,
      pages: 1,
    },
    isLoading: false,
  };
};
