"""form_roles

Revision ID: 391c19a6d782
Revises: 0d84e0bb9f6a
Create Date: 2022-06-22 12:26:28.642623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '391c19a6d782'
down_revision = '0d84e0bb9f6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('type', postgresql.ENUM('CLIENT', 'DESIGNER', 'REVIEWER', 'ANONYMOUS', name='roletype'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_roles_type'), 'tenant_roles', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_roles_type'), table_name='tenant_roles')
    op.drop_table('tenant_roles')
    # ### end Alembic commands ###
