"""empty message

Revision ID: a346f48423e5
Revises: 
Create Date: 2022-04-04 15:05:44.361353

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a346f48423e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
                    sa.Column('created_on', sa.DateTime(), nullable=True),
                    sa.Column('updated_on', sa.DateTime(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('key', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('details', sa.JSON(), nullable=False),
                    sa.Column('status', postgresql.ENUM('PENDING', 'ACTIVE', 'INACTIVE', 'EXPIRED', name='status'),
                              nullable=False),
                    sa.Column('created_by', sa.String(length=50), nullable=True),
                    sa.Column('updated_by', sa.String(length=50), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('key'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('tenant_clients',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('tenant_id', sa.Integer(), nullable=False),
                    sa.Column('client_type', postgresql.ENUM('WEB', 'ANALYTICS', 'BPM', name='clienttype'),
                              nullable=False),
                    sa.Column('client_id', sa.String(), nullable=True),
                    sa.Column('secret', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('tenant_contacts',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('tenant_id', sa.Integer(), nullable=False),
                    sa.Column('contact', sa.JSON(), nullable=False),
                    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_contacts')
    op.drop_table('tenant_clients')
    op.drop_table('tenants')
    # ### end Alembic commands ###
