"""tenant_expirty

Revision ID: e745376fb1f7
Revises: 339ddeb936bc
Create Date: 2022-09-28 16:05:08.137325

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e745376fb1f7'
down_revision = '339ddeb936bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('expiry_dt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'expiry_dt')
    # ### end Alembic commands ###
