apiVersion: apps/v1
kind: Deployment
metadata:
  name: form-flow-api
  namespace : forms-flow-api
  labels:
    app.kubernetes.io/name: formsflowapi
spec:
  replicas: 1
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: formsflowapi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: formsflowapi
    spec:
      imagePullSecrets:
        - name: private-registry
      containers:
        - name: formsflowapi
          image: sofiamunicipalitydigitall/forms-flow-api:latest
          lifecycle:
            postStart:
              exec:
                command: [ "/bin/sh", "-c",  "echo 'nameserver 8.8.8.8' >> /etc/resolv.conf && apt update && apt -y install cron vim  && env >> /etc/environment && crontab -l | { cat; echo '*/1 * * * * (FLASK_APP=/forms-flow-api/app/manage.py bash -c \"/venv/bin/flask cron expire-documents\") >> /var/log/expire_documents.log 2>&1'; echo '*/5 * * * * (FLASK_APP=/forms-flow-api/app/manage.py bash -c \"/venv/bin/flask cron delete-users\") >> /var/log/delete-users.log 2>&1'; echo '*/5 * * * * (FLASK_APP=/forms-flow-api/app/manage.py bash -c \"/venv/bin/flask cron update_obligation_payments_statuses\") >> /var/log/update_payments.log 2>&1'; echo '*/5 * * * * (FLASK_APP=/forms-flow-api/app/manage.py bash -c \"/venv/bin/flask mateus notify\") >> /var/log/mateus_notify.log 2>&1'; echo '@reboot (FLASK_APP=/forms-flow-api/app/manage.py bash -c \"/venv/bin/flask workers notification-worker\") >> /var/log/notification_worker.log 2>&1';} | crontab - && service cron start " ]
          ports:
            - containerPort: 5000
              name: http-api
              protocol: TCP
          volumeMounts:
            - mountPath: /mnt/external-services/acstre/documents
              name: documents
            - name: firebase
              mountPath: /opt/keycloak/firebase
            - name: logs
              mountPath: /mnt/mobile/logs
          env:
            - name: INSIGHT_API_KEY
              value: "MxlZK65GyqWuVM3ncZBLHTgNrgKr777w0vHxMdcG"
            - name: INSIGHT_API_URL
              value: "https://redash-dev-eservices.egov.bg"
            - name: DATABASE_URL
              value: "postgresql://api:YkKnskzt7B@172.23.230.134:5432/apidbdev"
            - name: BPM_TOKEN_API
              value: "https://identity-dev-eservices.egov.bg/auth/realms/eServices/protocol/openid-connect/token"
            - name: BPM_CLIENT_ID
              value: "forms-flow-bpm"
            - name: BPM_CLIENT_SECRET
              value: "SDi9yOoPH0wKncJw4fFlSkuZf6Ir5Lbc"
            - name: BPM_API_URL
              value: "http://forms-flow-bpm-svc.forms-flow-bpm.svc.cluster.local:8080/camunda"
            - name: FORMSFLOW_API_CORS_ORIGINS
              value: "*"
            - name: JWT_OIDC_WELL_KNOWN_CONFIG
              value: "https://identity-dev-eservices.egov.bg/auth/realms/eServices/.well-known/openid-configuration"
            - name: JWT_OIDC_JWKS_URI
              value: "https://identity-dev-eservices.egov.bg/auth/realms/eServices/protocol/openid-connect/certs"
            - name: JWT_OIDC_ISSUER
              value: "https://identity-dev-eservices.egov.bg/auth/realms/eServices"
            - name: JWT_OIDC_AUDIENCE
              value: "forms-flow-web"
            - name: JWT_OIDC_CACHING_ENABLED
              value: "True"
            - name: KEYCLOAK_URL
              value: "https://identity-dev-eservices.egov.bg"
            - name: KEYCLOAK_URL_REALM
              value: "eServices"
            - name: WEB_API_BASE_URL
              value: "https://api-dev-eservices.egov.bg"
            - name: WEB_BASE_URL
              value: "https://dev-eservices.sofia.bg"
            - name: FORMIO_WEB_URL
              value: "https://forms-dev-eservices.egov.bg"
            - name: FORMIO_URL
              value: "http://forms-flow-forms-svc.forms-flow-forms.svc.cluster.local:3001"
            - name: MULTI_TENANCY_ENABLED
              value: "true"
            - name: KEYCLOAK_ENABLE_CLIENT_AUTH
              value: "true"
            - name: FORM_EMBED_JWT_SECRET
              value: "f6a69a42-7f8a-11ed-a1eb-0242ac120002"
            - name: FORMIO_ROOT_EMAIL
              value: "iiliev@digitall.com"
            - name: FORMIO_ROOT_PASSWORD
              value: "fd1cnUW2Rp608S2"
            - name: FORMIO_JWT_SECRET
              value: "test-secret"
            - name: FORMIO_FILE_RESOURCE_PATH
              value: "generated-files"
            - name: CRON_DOCUMENT_TRANSACTION_TIMEOUT
              value: "1"
            - name: EUROTRUST_EXPIRE_TIMEOUT
              value: "30"
            - name: EFORM_INTEGRATIONS_URL
              value: "http://forms-flow-eforms-integrations-svc.form-flow-eforms-integrations.svc.cluster.local:8002"
            - name: FORMSFLOW_DOC_API_URL
              value: "http://forms-flow-documents-svc.forms-flow-documents.svc.cluster.local:5006"
            - name: SIGN_SERVICE_API_URL
              value: "http://signature-services-svc.forms-flow-eforms-signature-services.svc.cluster.local:8004/api"
            - name: EUROTRUST_IDENTITY_TIMEOUT
              value: "30"
            - name: EVROTRUST_IDENTITY_REQUESTS_MAX_RETRIES
              value: "15"
            - name: EVROTRUST_IDENTITY_AUTHENTICATE_TIMEOUT
              value: "3"
            - name: FIREBASE_CREDENTIALS_PATH
              value: "/opt/keycloak/firebase/firebase-service-account.json"
            - name: OTHER_FILE_DESTINATION
              value: "/mnt/external-services/acstre/documents/"
            - name: MOBILE_LOGS_FILE_DESTINATION
              value: "/mnt/mobile/logs/"
            - name: MATEUS_COMPANY_ID
              value: "999"
            - name: CAMUNDA_CHANGE_ADDRESS_PROCESS
              value: "Process_sofiade"
            - name: REDIS_CONNECTION
              value: "redis://redis-master.redis.svc.cluster.local:6379/0"
            - name: "REDIS_KEY_TTL"
              value: "300"
            - name: REDIS_PASSWORD
              value: ""
            - name: REGIONS_SECRET_KEY
              value: ""
            - name: MESSAGE_BUS_URL
              value: "amqp://forms-flow-api:5FmW93M6fWvv@rabbitmq.rabbitmq.svc.cluster.local//"
            - name: SERVICE_URL
              value: "http://forms-flow-eforms-integrations-svc.form-flow-eforms-integrations.svc.cluster.local:8002/integrations/notifications/post-mail-notification"
            - name: "NOTIFICATION_SCHEMA"
              value: "300,3600,3600,3600,3600"
            - name: MATEUS_PAYMENT_CLIENT_ID
              value: ""
            - name: MATEUS_PAYMENT_CLIENT_SECRET
              value: ""
      volumes:
        - name: documents
          nfs:
            path: /pvc/documents
            server: 172.23.230.140
        - name: firebase
          nfs:
            server: 172.23.230.140
            path: /pvc/keycloak/firebase
        - name: logs
          nfs:
            server: 172.23.230.140
            path: /pvc/logs