package com.bulpros.integrations.eDelivery.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2022-01-09T12:15:42.558+02:00
 * Generated source version: 3.4.3
 *
 */
@WebService(targetNamespace = "https://edelivery.egov.bg/services/integration", name = "IEDeliveryIntegrationService")
@XmlSeeAlso({ObjectFactory.class})
public interface IEDeliveryIntegrationService {

    @WebMethod(operationName = "SendElectronicDocumentOnBehalfOf", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendElectronicDocumentOnBehalfOf")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendElectronicDocumentOnBehalfOf", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendElectronicDocumentOnBehalfOfResponse")
    @RequestWrapper(localName = "SendElectronicDocumentOnBehalfOf", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.SendElectronicDocumentOnBehalfOf")
    @ResponseWrapper(localName = "SendElectronicDocumentOnBehalfOfResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.SendElectronicDocumentOnBehalfOfResponse")
    @WebResult(name = "SendElectronicDocumentOnBehalfOfResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public java.lang.Integer sendElectronicDocumentOnBehalfOf(

        @WebParam(name = "subject", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String subject,
        @WebParam(name = "docBytes", targetNamespace = "https://edelivery.egov.bg/services/integration")
        byte[] docBytes,
        @WebParam(name = "docNameWithExtension", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String docNameWithExtension,
        @WebParam(name = "docRegNumber", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String docRegNumber,
        @WebParam(name = "senderType", targetNamespace = "https://edelivery.egov.bg/services/integration")
        com.bulpros.integrations.eDelivery.model.EProfileType senderType,
        @WebParam(name = "senderUniqueIdentifier", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String senderUniqueIdentifier,
        @WebParam(name = "senderPhone", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String senderPhone,
        @WebParam(name = "senderEmail", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String senderEmail,
        @WebParam(name = "senderFirstName", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String senderFirstName,
        @WebParam(name = "senderLastName", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String senderLastName,
        @WebParam(name = "receiverType", targetNamespace = "https://edelivery.egov.bg/services/integration")
        com.bulpros.integrations.eDelivery.model.EProfileType receiverType,
        @WebParam(name = "receiverUniqueIdentifier", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String receiverUniqueIdentifier,
        @WebParam(name = "serviceOID", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String serviceOID,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "CheckSubjectHasRegistration", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/CheckSubjectHasRegistration")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/CheckSubjectHasRegistration", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/CheckSubjectHasRegistrationResponse")
    @RequestWrapper(localName = "CheckSubjectHasRegistration", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.CheckSubjectHasRegistration")
    @ResponseWrapper(localName = "CheckSubjectHasRegistrationResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.CheckSubjectHasRegistrationResponse")
    @WebResult(name = "CheckSubjectHasRegistrationResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public com.bulpros.integrations.eDelivery.model.DcSubjectRegistrationInfo checkSubjectHasRegistration(

        @WebParam(name = "identificator", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String identificator
    );

    @WebMethod(operationName = "GetSubjectInfo", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSubjectInfo")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSubjectInfo", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSubjectInfoResponse")
    @RequestWrapper(localName = "GetSubjectInfo", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.GetSubjectInfo")
    @ResponseWrapper(localName = "GetSubjectInfoResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.GetSubjectInfoResponse")
    @WebResult(name = "GetSubjectInfoResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public com.bulpros.integrations.eDelivery.model.DcSubjectInfo getSubjectInfo(

        @WebParam(name = "electronicSubjectId", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String electronicSubjectId,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "GetRegisteredInstitutions", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetRegisteredInstitutions")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetRegisteredInstitutions", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetRegisteredInstitutionsResponse")
    @RequestWrapper(localName = "GetRegisteredInstitutions", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.GetRegisteredInstitutions")
    @ResponseWrapper(localName = "GetRegisteredInstitutionsResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.GetRegisteredInstitutionsResponse")
    @WebResult(name = "GetRegisteredInstitutionsResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public com.bulpros.integrations.eDelivery.model.ArrayOfDcInstitutionInfo getRegisteredInstitutions()
;

    @WebMethod(operationName = "GetReceivedMessagesList", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetReceivedMessagesList")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetReceivedMessagesList", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetReceivedMessagesListResponse")
    @RequestWrapper(localName = "GetReceivedMessagesList", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.GetReceivedMessagesList")
    @ResponseWrapper(localName = "GetReceivedMessagesListResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.GetReceivedMessagesListResponse")
    @WebResult(name = "GetReceivedMessagesListResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public com.bulpros.integrations.eDelivery.model.ArrayOfDcMessage getReceivedMessagesList(

        @WebParam(name = "onlyNew", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.Boolean onlyNew,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "SendMessageOnBehalfOf", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendMessageOnBehalfOf")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendMessageOnBehalfOf", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendMessageOnBehalfOfResponse")
    @RequestWrapper(localName = "SendMessageOnBehalfOf", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.SendMessageOnBehalfOf")
    @ResponseWrapper(localName = "SendMessageOnBehalfOfResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.SendMessageOnBehalfOfResponse")
    @WebResult(name = "SendMessageOnBehalfOfResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public java.lang.Integer sendMessageOnBehalfOf(

        @WebParam(name = "message", targetNamespace = "https://edelivery.egov.bg/services/integration")
        com.bulpros.integrations.eDelivery.model.DcMessageDetails message,
        @WebParam(name = "senderType", targetNamespace = "https://edelivery.egov.bg/services/integration")
        com.bulpros.integrations.eDelivery.model.EProfileType senderType,
        @WebParam(name = "senderUniqueIdentifier", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String senderUniqueIdentifier,
        @WebParam(name = "senderPhone", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String senderPhone,
        @WebParam(name = "senderEmail", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String senderEmail,
        @WebParam(name = "senderFirstName", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String senderFirstName,
        @WebParam(name = "senderLastName", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String senderLastName,
        @WebParam(name = "receiverType", targetNamespace = "https://edelivery.egov.bg/services/integration")
        com.bulpros.integrations.eDelivery.model.EProfileType receiverType,
        @WebParam(name = "receiverUniqueIdentifier", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String receiverUniqueIdentifier,
        @WebParam(name = "serviceOID", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String serviceOID,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "SendElectronicDocument", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendElectronicDocument")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendElectronicDocument", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendElectronicDocumentResponse")
    @RequestWrapper(localName = "SendElectronicDocument", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.SendElectronicDocument")
    @ResponseWrapper(localName = "SendElectronicDocumentResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.SendElectronicDocumentResponse")
    @WebResult(name = "SendElectronicDocumentResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public java.lang.Integer sendElectronicDocument(

        @WebParam(name = "subject", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String subject,
        @WebParam(name = "docBytes", targetNamespace = "https://edelivery.egov.bg/services/integration")
        byte[] docBytes,
        @WebParam(name = "docNameWithExtension", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String docNameWithExtension,
        @WebParam(name = "docRegNumber", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String docRegNumber,
        @WebParam(name = "receiverType", targetNamespace = "https://edelivery.egov.bg/services/integration")
        com.bulpros.integrations.eDelivery.model.EProfileType receiverType,
        @WebParam(name = "receiverUniqueIdentifier", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String receiverUniqueIdentifier,
        @WebParam(name = "receiverPhone", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String receiverPhone,
        @WebParam(name = "receiverEmail", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String receiverEmail,
        @WebParam(name = "serviceOID", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String serviceOID,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "SendMessage", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendMessage")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendMessage", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendMessageResponse")
    @RequestWrapper(localName = "SendMessage", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.SendMessage")
    @ResponseWrapper(localName = "SendMessageResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.SendMessageResponse")
    @WebResult(name = "SendMessageResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public java.lang.Integer sendMessage(

        @WebParam(name = "message", targetNamespace = "https://edelivery.egov.bg/services/integration")
        com.bulpros.integrations.eDelivery.model.DcMessageDetails message,
        @WebParam(name = "receiverType", targetNamespace = "https://edelivery.egov.bg/services/integration")
        com.bulpros.integrations.eDelivery.model.EProfileType receiverType,
        @WebParam(name = "receiverUniqueIdentifier", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String receiverUniqueIdentifier,
        @WebParam(name = "receiverPhone", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String receiverPhone,
        @WebParam(name = "receiverEmail", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String receiverEmail,
        @WebParam(name = "serviceOID", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String serviceOID,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "GetReceivedMessagesListPaged", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetReceivedMessagesListPaged")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetReceivedMessagesListPaged", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetReceivedMessagesListPagedResponse")
    @RequestWrapper(localName = "GetReceivedMessagesListPaged", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.GetReceivedMessagesListPaged")
    @ResponseWrapper(localName = "GetReceivedMessagesListPagedResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.GetReceivedMessagesListPagedResponse")
    @WebResult(name = "GetReceivedMessagesListPagedResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public com.bulpros.integrations.eDelivery.model.DcPartialListOfDcMessageHR29GRRX getReceivedMessagesListPaged(

        @WebParam(name = "onlyNew", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.Boolean onlyNew,
        @WebParam(name = "pageNumber", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.Integer pageSize,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "SendMessageOnBehalfToPerson", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendMessageOnBehalfToPerson")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendMessageOnBehalfToPerson", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendMessageOnBehalfToPersonResponse")
    @RequestWrapper(localName = "SendMessageOnBehalfToPerson", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.SendMessageOnBehalfToPerson")
    @ResponseWrapper(localName = "SendMessageOnBehalfToPersonResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.SendMessageOnBehalfToPersonResponse")
    @WebResult(name = "SendMessageOnBehalfToPersonResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public java.lang.Integer sendMessageOnBehalfToPerson(

        @WebParam(name = "message", targetNamespace = "https://edelivery.egov.bg/services/integration")
        com.bulpros.integrations.eDelivery.model.DcMessageDetails message,
        @WebParam(name = "senderUniqueIdentifier", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String senderUniqueIdentifier,
        @WebParam(name = "receiverUniqueIdentifier", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String receiverUniqueIdentifier,
        @WebParam(name = "receiverPhone", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String receiverPhone,
        @WebParam(name = "receiverEmail", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String receiverEmail,
        @WebParam(name = "receiverFirstName", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String receiverFirstName,
        @WebParam(name = "receiverLastName", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String receiverLastName,
        @WebParam(name = "serviceOID", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String serviceOID,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "GetSentDocumentsContent", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentDocumentsContent")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentDocumentsContent", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentDocumentsContentResponse")
    @RequestWrapper(localName = "GetSentDocumentsContent", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.GetSentDocumentsContent")
    @ResponseWrapper(localName = "GetSentDocumentsContentResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.GetSentDocumentsContentResponse")
    @WebResult(name = "GetSentDocumentsContentResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public com.bulpros.integrations.eDelivery.model.ArrayOfDcDocument getSentDocumentsContent(

        @WebParam(name = "messageId", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.Integer messageId,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "GetSentMessagesListPaged", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentMessagesListPaged")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentMessagesListPaged", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentMessagesListPagedResponse")
    @RequestWrapper(localName = "GetSentMessagesListPaged", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.GetSentMessagesListPaged")
    @ResponseWrapper(localName = "GetSentMessagesListPagedResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.GetSentMessagesListPagedResponse")
    @WebResult(name = "GetSentMessagesListPagedResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public com.bulpros.integrations.eDelivery.model.DcPartialListOfDcMessageHR29GRRX getSentMessagesListPaged(

        @WebParam(name = "pageNumber", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.Integer pageSize,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "SendMessageInReplyTo", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendMessageInReplyTo")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendMessageInReplyTo", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendMessageInReplyToResponse")
    @RequestWrapper(localName = "SendMessageInReplyTo", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.SendMessageInReplyTo")
    @ResponseWrapper(localName = "SendMessageInReplyToResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.SendMessageInReplyToResponse")
    @WebResult(name = "SendMessageInReplyToResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public java.lang.Integer sendMessageInReplyTo(

        @WebParam(name = "message", targetNamespace = "https://edelivery.egov.bg/services/integration")
        com.bulpros.integrations.eDelivery.model.DcMessageDetails message,
        @WebParam(name = "replyToMessageId", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.Integer replyToMessageId,
        @WebParam(name = "serviceOID", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String serviceOID,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "GetEDeliveryGeneralStatistics", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetEDeliveryGeneralStatistics")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetEDeliveryGeneralStatistics", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetEDeliveryGeneralStatisticsResponse")
    @RequestWrapper(localName = "GetEDeliveryGeneralStatistics", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.GetEDeliveryGeneralStatistics")
    @ResponseWrapper(localName = "GetEDeliveryGeneralStatisticsResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.GetEDeliveryGeneralStatisticsResponse")
    @WebResult(name = "GetEDeliveryGeneralStatisticsResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public com.bulpros.integrations.eDelivery.model.DcStatisticsGeneral getEDeliveryGeneralStatistics()
;

    @WebMethod(operationName = "GetSentMessageStatus", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentMessageStatus")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentMessageStatus", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentMessageStatusResponse")
    @RequestWrapper(localName = "GetSentMessageStatus", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.GetSentMessageStatus")
    @ResponseWrapper(localName = "GetSentMessageStatusResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.GetSentMessageStatusResponse")
    @WebResult(name = "GetSentMessageStatusResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public com.bulpros.integrations.eDelivery.model.DcMessageDetails getSentMessageStatus(

        @WebParam(name = "messageId", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.Integer messageId,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "CheckPersonHasRegistration", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/CheckPersonHasRegistration")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/CheckPersonHasRegistration", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/CheckPersonHasRegistrationResponse")
    @RequestWrapper(localName = "CheckPersonHasRegistration", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.CheckPersonHasRegistration")
    @ResponseWrapper(localName = "CheckPersonHasRegistrationResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.CheckPersonHasRegistrationResponse")
    @WebResult(name = "CheckPersonHasRegistrationResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public com.bulpros.integrations.eDelivery.model.DcPersonRegistrationInfo checkPersonHasRegistration(

        @WebParam(name = "personId", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String personId
    );

    @WebMethod(operationName = "CheckLegalPersonHasRegistration", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/CheckLegalPersonHasRegistration")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/CheckLegalPersonHasRegistration", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/CheckLegalPersonHasRegistrationResponse")
    @RequestWrapper(localName = "CheckLegalPersonHasRegistration", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.CheckLegalPersonHasRegistration")
    @ResponseWrapper(localName = "CheckLegalPersonHasRegistrationResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.CheckLegalPersonHasRegistrationResponse")
    @WebResult(name = "CheckLegalPersonHasRegistrationResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public com.bulpros.integrations.eDelivery.model.DcLegalPersonRegistrationInfo checkLegalPersonHasRegistration(

        @WebParam(name = "eik", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String eik
    );

    @WebMethod(operationName = "SendMessageWithAccessCode", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendMessageWithAccessCode")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendMessageWithAccessCode", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendMessageWithAccessCodeResponse")
    @RequestWrapper(localName = "SendMessageWithAccessCode", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.SendMessageWithAccessCode")
    @ResponseWrapper(localName = "SendMessageWithAccessCodeResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.SendMessageWithAccessCodeResponse")
    @WebResult(name = "SendMessageWithAccessCodeResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public java.lang.Integer sendMessageWithAccessCode(

        @WebParam(name = "message", targetNamespace = "https://edelivery.egov.bg/services/integration")
        com.bulpros.integrations.eDelivery.model.DcMessageDetails message,
        @WebParam(name = "receiver", targetNamespace = "https://edelivery.egov.bg/services/integration")
        com.bulpros.integrations.eDelivery.model.DcMessageWithCodeReceiver receiver,
        @WebParam(name = "serviceOID", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String serviceOID,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "GetSentMessagesList", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentMessagesList")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentMessagesList", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentMessagesListResponse")
    @RequestWrapper(localName = "GetSentMessagesList", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.GetSentMessagesList")
    @ResponseWrapper(localName = "GetSentMessagesListResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.GetSentMessagesListResponse")
    @WebResult(name = "GetSentMessagesListResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public com.bulpros.integrations.eDelivery.model.ArrayOfDcMessage getSentMessagesList(

        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "SendMessageOnBehalfToLegalEntity", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendMessageOnBehalfToLegalEntity")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendMessageOnBehalfToLegalEntity", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendMessageOnBehalfToLegalEntityResponse")
    @RequestWrapper(localName = "SendMessageOnBehalfToLegalEntity", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.SendMessageOnBehalfToLegalEntity")
    @ResponseWrapper(localName = "SendMessageOnBehalfToLegalEntityResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.SendMessageOnBehalfToLegalEntityResponse")
    @WebResult(name = "SendMessageOnBehalfToLegalEntityResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public java.lang.Integer sendMessageOnBehalfToLegalEntity(

        @WebParam(name = "message", targetNamespace = "https://edelivery.egov.bg/services/integration")
        com.bulpros.integrations.eDelivery.model.DcMessageDetails message,
        @WebParam(name = "senderUniqueIdentifier", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String senderUniqueIdentifier,
        @WebParam(name = "receiverUniqueIdentifier", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String receiverUniqueIdentifier,
        @WebParam(name = "serviceOID", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String serviceOID,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "GetSentDocumentContent", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentDocumentContent")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentDocumentContent", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentDocumentContentResponse")
    @RequestWrapper(localName = "GetSentDocumentContent", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.GetSentDocumentContent")
    @ResponseWrapper(localName = "GetSentDocumentContentResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.GetSentDocumentContentResponse")
    @WebResult(name = "GetSentDocumentContentResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public com.bulpros.integrations.eDelivery.model.DcDocument getSentDocumentContent(

        @WebParam(name = "documentId", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.Integer documentId,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "GetSentMessageContent", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentMessageContent")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentMessageContent", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentMessageContentResponse")
    @RequestWrapper(localName = "GetSentMessageContent", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.GetSentMessageContent")
    @ResponseWrapper(localName = "GetSentMessageContentResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.GetSentMessageContentResponse")
    @WebResult(name = "GetSentMessageContentResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public com.bulpros.integrations.eDelivery.model.DcMessageDetails getSentMessageContent(

        @WebParam(name = "messageId", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.Integer messageId,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "GetReceivedMessageContent", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetReceivedMessageContent")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetReceivedMessageContent", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetReceivedMessageContentResponse")
    @RequestWrapper(localName = "GetReceivedMessageContent", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.GetReceivedMessageContent")
    @ResponseWrapper(localName = "GetReceivedMessageContentResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.GetReceivedMessageContentResponse")
    @WebResult(name = "GetReceivedMessageContentResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public com.bulpros.integrations.eDelivery.model.DcMessageDetails getReceivedMessageContent(

        @WebParam(name = "messageId", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.Integer messageId,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "SendElectronicDocumentWithAccessCode", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendElectronicDocumentWithAccessCode")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendElectronicDocumentWithAccessCode", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendElectronicDocumentWithAccessCodeResponse")
    @RequestWrapper(localName = "SendElectronicDocumentWithAccessCode", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.SendElectronicDocumentWithAccessCode")
    @ResponseWrapper(localName = "SendElectronicDocumentWithAccessCodeResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.SendElectronicDocumentWithAccessCodeResponse")
    @WebResult(name = "SendElectronicDocumentWithAccessCodeResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public java.lang.Integer sendElectronicDocumentWithAccessCode(

        @WebParam(name = "subject", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String subject,
        @WebParam(name = "docBytes", targetNamespace = "https://edelivery.egov.bg/services/integration")
        byte[] docBytes,
        @WebParam(name = "docNameWithExtension", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String docNameWithExtension,
        @WebParam(name = "docRegNumber", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String docRegNumber,
        @WebParam(name = "receiver", targetNamespace = "https://edelivery.egov.bg/services/integration")
        com.bulpros.integrations.eDelivery.model.DcMessageWithCodeReceiver receiver,
        @WebParam(name = "serviceOID", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String serviceOID,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "GetSentDocumentStatusByRegNum", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentDocumentStatusByRegNum")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentDocumentStatusByRegNum", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentDocumentStatusByRegNumResponse")
    @RequestWrapper(localName = "GetSentDocumentStatusByRegNum", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.GetSentDocumentStatusByRegNum")
    @ResponseWrapper(localName = "GetSentDocumentStatusByRegNumResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.GetSentDocumentStatusByRegNumResponse")
    @WebResult(name = "GetSentDocumentStatusByRegNumResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public com.bulpros.integrations.eDelivery.model.DcMessageDetails getSentDocumentStatusByRegNum(

        @WebParam(name = "documentRegistrationNumber", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String documentRegistrationNumber,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "GetSentDocumentContentByRegNum", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentDocumentContentByRegNum")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentDocumentContentByRegNum", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentDocumentContentByRegNumResponse")
    @RequestWrapper(localName = "GetSentDocumentContentByRegNum", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.GetSentDocumentContentByRegNum")
    @ResponseWrapper(localName = "GetSentDocumentContentByRegNumResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "com.bulpros.integrations.eDelivery.model.GetSentDocumentContentByRegNumResponse")
    @WebResult(name = "GetSentDocumentContentByRegNumResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public com.bulpros.integrations.eDelivery.model.DcDocument getSentDocumentContentByRegNum(

        @WebParam(name = "documentRegistrationNumber", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String documentRegistrationNumber,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );
}
