//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.26 at 07:37:26 PM EEST 
//


package com.bulpros.integrations.regix.model.MON.GetHigherEduStudentByStatus;

import javax.xml.bind.annotation.*;


/**
 * Входни параметри на справка за всички студенти или докторанти със статус "действащ" и "отчислен с право на защита", по подаден идентификатор
 * 
 * <p>Java class for HigherEduStudentByStatusRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HigherEduStudentByStatusRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="StudentIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="StudentStatus" type="{http://egov.bg/RegiX/MON/HigherEdu/HigherEduStudentByStatusRequest}StudentStatusType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HigherEduStudentByStatusRequestType", namespace = "http://egov.bg/RegiX/MON/HigherEdu/HigherEduStudentByStatusRequest", propOrder = {
    "studentIdentifier",
    "studentStatus"
})
@XmlRootElement(name = "HigherEduStudentByStatusRequest", namespace = "http://egov.bg/RegiX/MON/HigherEdu/HigherEduStudentByStatusRequest")
public class HigherEduStudentByStatusRequestType {

    @XmlElement(name = "StudentIdentifier", required = true)
    protected String studentIdentifier;
    @XmlElement(name = "StudentStatus", required = true)
    @XmlSchemaType(name = "string")
    protected StudentStatusType studentStatus;

    /**
     * Gets the value of the studentIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStudentIdentifier() {
        return studentIdentifier;
    }

    /**
     * Sets the value of the studentIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStudentIdentifier(String value) {
        this.studentIdentifier = value;
    }

    /**
     * Gets the value of the studentStatus property.
     * 
     * @return
     *     possible object is
     *     {@link StudentStatusType }
     *     
     */
    public StudentStatusType getStudentStatus() {
        return studentStatus;
    }

    /**
     * Sets the value of the studentStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudentStatusType }
     *     
     */
    public void setStudentStatus(StudentStatusType value) {
        this.studentStatus = value;
    }

}
