//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.26 at 07:37:26 PM EEST 
//


package com.bulpros.integrations.regix.model.MON.GetHigherEduStudentByStatus;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StudentStatusType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="StudentStatusType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="active"/&gt;
 *     &lt;enumeration value="graduationright"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "StudentStatusType", namespace = "http://egov.bg/RegiX/MON/HigherEdu/HigherEduStudentByStatusRequest")
@XmlEnum
public enum StudentStatusType {


    /**
     * действащ
     * 
     */
    @XmlEnumValue("active")
    ACTIVE("active"),

    /**
     * отчислен с право на защита
     * 
     */
    @XmlEnumValue("graduationright")
    GRADUATIONRIGHT("graduationright");
    private final String value;

    StudentStatusType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StudentStatusType fromValue(String v) {
        for (StudentStatusType c: StudentStatusType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
