//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.26 at 07:37:26 PM EEST 
//


package com.bulpros.integrations.regix.model.MON.GetHigherEduStudentByStatus;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Данни за студент или докторант в Регистъра на действащите и прекъснали студенти и докторанти на МОН
 * 
 * <p>Java class for StudentData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StudentData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="StudentIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MiddleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Nationality" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="HigherSchoolName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="HigherSchollLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FacultyName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EducationalYear" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Semester" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AcquiredDegree" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ProfessionalField" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Subject" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EducationalCourse" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EducationalForm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="StudentStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FacultyNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UpdateDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StudentData", namespace = "http://egov.bg/RegiX/MON/HigherEdu/Common", propOrder = {
    "studentIdentifier",
    "firstName",
    "middleName",
    "lastName",
    "nationality",
    "higherSchoolName",
    "higherSchollLocation",
    "facultyName",
    "educationalYear",
    "semester",
    "acquiredDegree",
    "professionalField",
    "subject",
    "educationalCourse",
    "educationalForm",
    "studentStatus",
    "facultyNumber",
    "updateDate"
})
public class StudentData {

    @XmlElement(name = "StudentIdentifier")
    protected String studentIdentifier;
    @XmlElement(name = "FirstName")
    protected String firstName;
    @XmlElement(name = "MiddleName")
    protected String middleName;
    @XmlElement(name = "LastName")
    protected String lastName;
    @XmlElement(name = "Nationality")
    protected String nationality;
    @XmlElement(name = "HigherSchoolName")
    protected String higherSchoolName;
    @XmlElement(name = "HigherSchollLocation")
    protected String higherSchollLocation;
    @XmlElement(name = "FacultyName")
    protected String facultyName;
    @XmlElement(name = "EducationalYear")
    protected Integer educationalYear;
    @XmlElement(name = "Semester")
    protected String semester;
    @XmlElement(name = "AcquiredDegree")
    protected String acquiredDegree;
    @XmlElement(name = "ProfessionalField")
    protected String professionalField;
    @XmlElement(name = "Subject")
    protected String subject;
    @XmlElement(name = "EducationalCourse")
    protected String educationalCourse;
    @XmlElement(name = "EducationalForm")
    protected String educationalForm;
    @XmlElement(name = "StudentStatus")
    protected String studentStatus;
    @XmlElement(name = "FacultyNumber")
    protected String facultyNumber;
    @XmlElement(name = "UpdateDate")
    protected String updateDate;

    /**
     * Gets the value of the studentIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStudentIdentifier() {
        return studentIdentifier;
    }

    /**
     * Sets the value of the studentIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStudentIdentifier(String value) {
        this.studentIdentifier = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleName(String value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the nationality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * Sets the value of the nationality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationality(String value) {
        this.nationality = value;
    }

    /**
     * Gets the value of the higherSchoolName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHigherSchoolName() {
        return higherSchoolName;
    }

    /**
     * Sets the value of the higherSchoolName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHigherSchoolName(String value) {
        this.higherSchoolName = value;
    }

    /**
     * Gets the value of the higherSchollLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHigherSchollLocation() {
        return higherSchollLocation;
    }

    /**
     * Sets the value of the higherSchollLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHigherSchollLocation(String value) {
        this.higherSchollLocation = value;
    }

    /**
     * Gets the value of the facultyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacultyName() {
        return facultyName;
    }

    /**
     * Sets the value of the facultyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacultyName(String value) {
        this.facultyName = value;
    }

    /**
     * Gets the value of the educationalYear property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEducationalYear() {
        return educationalYear;
    }

    /**
     * Sets the value of the educationalYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEducationalYear(Integer value) {
        this.educationalYear = value;
    }

    /**
     * Gets the value of the semester property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSemester() {
        return semester;
    }

    /**
     * Sets the value of the semester property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSemester(String value) {
        this.semester = value;
    }

    /**
     * Gets the value of the acquiredDegree property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcquiredDegree() {
        return acquiredDegree;
    }

    /**
     * Sets the value of the acquiredDegree property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcquiredDegree(String value) {
        this.acquiredDegree = value;
    }

    /**
     * Gets the value of the professionalField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfessionalField() {
        return professionalField;
    }

    /**
     * Sets the value of the professionalField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfessionalField(String value) {
        this.professionalField = value;
    }

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubject(String value) {
        this.subject = value;
    }

    /**
     * Gets the value of the educationalCourse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEducationalCourse() {
        return educationalCourse;
    }

    /**
     * Sets the value of the educationalCourse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEducationalCourse(String value) {
        this.educationalCourse = value;
    }

    /**
     * Gets the value of the educationalForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEducationalForm() {
        return educationalForm;
    }

    /**
     * Sets the value of the educationalForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEducationalForm(String value) {
        this.educationalForm = value;
    }

    /**
     * Gets the value of the studentStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStudentStatus() {
        return studentStatus;
    }

    /**
     * Sets the value of the studentStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStudentStatus(String value) {
        this.studentStatus = value;
    }

    /**
     * Gets the value of the facultyNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacultyNumber() {
        return facultyNumber;
    }

    /**
     * Sets the value of the facultyNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacultyNumber(String value) {
        this.facultyNumber = value;
    }

    /**
     * Gets the value of the updateDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * Sets the value of the updateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdateDate(String value) {
        this.updateDate = value;
    }

}
