import { PAGE_NAMES, PAGE_BLOCKS } from "../../../constants/pages";

const contactsPageBlogs = PAGE_BLOCKS[PAGE_NAMES.CONTACTS_PAGE];

export default {
  bg: {
    [contactsPageBlogs.CONTACTS_BLOCK]: {
      items: [
        {
          link: "https://bankya.bg/",
          region: "Банкя",
          mdtName: "ОТДЕЛ МДТ",
          graoName: "ОТДЕЛ ГРАО",
          mdtPhone1: "029977045",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "029977261",
          graoPhone2: "029977029101",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://raionvitosha.eu/bg/",
          region: "Витоша",
          mdtName: "ОТДЕЛ МДТ",
          graoName: "ОТДЕЛ ГРАО",
          mdtPhone1: "029555953",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "028187918",
          graoPhone2: "",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://raionvitosha.eu/bg/",
          region: "Връбница",
          mdtName: "ОТДЕЛ МДТ",
          graoName: "ОТДЕЛ ГРАО",
          mdtPhone1: "029041188",
          mdtPhone2: "029041191",
          mdtPhone3: "029041193",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "024957740",
          graoPhone2: "024957707",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://www.so-vazrajdane.bg/",
          region: "Възраждане",
          mdtName: "ОТДЕЛ МДТ",
          graoName: "ОТДЕЛ ГРАО",
          mdtPhone1: "029041196",
          mdtPhone2: "029041197",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "029814364",
          graoPhone2: "",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://rayon-oborishte.bg/",
          region: "Оборище",
          mdtName: "ОТДЕЛ МДТ",
          graoName: "ОТДЕЛ ГРАО",
          mdtPhone1: "029434835",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "029431840",
          graoPhone2: "",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://so-izgrev.bg/",
          region: "Изгрев",
          mdtName: "ОТДЕЛ МДТ",
          graoName: "ОТДЕЛ ГРАО",
          mdtPhone1: "029041220",
          mdtPhone2: "029041219",
          mdtPhone3: "029041218",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "029701025",
          graoPhone2: "",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://lozenets.sofia.bg/",
          region: "Лозенец",
          mdtName: "ОТДЕЛ МДТ",
          graoName: "ОТДЕЛ ГРАО",
          mdtPhone1: "029800912",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "070020555",
          graoPhone2: "",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "http://www.serdika.bg/",
          region: "Сердика",
          mdtName: "ОТДЕЛ МДТ",
          graoName: "ОТДЕЛ ГРАО",
          mdtPhone1: "029311478",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "028322095",
          graoPhone2: " 029218017",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://so-slatina.org/",
          region: "Слатина",
          mdtName: "ОТДЕЛ МДТ",
          graoName: "ОТДЕЛ ГРАО",
          mdtPhone1: "029311478",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "028709246",
          graoPhone2: " 028703218",
          graoPhone3: "028731482",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://sredec-sofia.org/",
          region: "Средец",
          mdtName: "ОТДЕЛ МДТ Средец и Триадица",
          graoName: "ОТДЕЛ ГРАО",
          mdtPhone1: "029809076",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "029484317",
          graoPhone2: "",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://triaditza.org/",
          region: "Триадица",
          mdtName: "ОТДЕЛ МДТ Средец и Триадица",
          graoName: "ОТДЕЛ ГРАО Триадица",
          mdtPhone1: "029809076",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "028054117",
          graoPhone2: "028054119",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://www.krasnapoliana.com/",
          region: "Красна поляна",
          mdtName: "ОТДЕЛ МДТ",
          graoName: "ОТДЕЛ ГРАО",
          mdtPhone1: "029201624",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "029217256",
          graoPhone2: "029217237",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://www.krasnoselo.net/",
          region: "Красно село",
          mdtName: "ОТДЕЛ МДТ",
          graoName: "ОТДЕЛ ГРАО",
          mdtPhone1: "029557325",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "028951142",
          graoPhone2: "",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "http://kremikovci.org/",
          region: "Кремиковци",
          mdtName: "ОТДЕЛ МДТ",
          graoName: "ОТДЕЛ ГРАО",
          mdtPhone1: "029945672",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "029945491",
          graoPhone2: "",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "http://www.pancharevo.org/",
          region: "Панчарево",
          mdtName: "ОТДЕЛ МДТ",
          graoName: "ОТДЕЛ ГРАО",
          mdtPhone1: "029041234",
          mdtPhone2: "029041235",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "029760506",
          graoPhone2: "029923120",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://www.poduiane.info/",
          region: "Подуяне",
          mdtName: "ОТДЕЛ МДТ",
          graoName: "ОТДЕЛ ГРАО",
          mdtPhone1: "029455287",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "028146100",
          graoPhone2: "",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://www.ilinden.bg/",
          region: "Илинден",
          mdtName: "ОТДЕЛ МДТ",
          graoName: "ОТДЕЛ ГРАО",
          mdtPhone1: "028211265",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "024397322",
          graoPhone2: "024397322",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://raioniskar.bg/",
          region: "Искър",
          mdtName: "ОТДЕЛ МДТ",
          graoName: "ОТДЕЛ ГРАО",
          mdtPhone1: "029790572",
          mdtPhone2: "029790450",
          mdtPhone3: "029794897",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "029790740",
          graoPhone2: "",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "http://www.novi-iskar.bg/",
          region: "Нови Искър",
          mdtName: "ОТДЕЛ МДТ",
          graoName: "ОТДЕЛ ГРАО",
          mdtPhone1: "029918381",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "029917230",
          graoPhone2: "",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://www.lyulin.bg/",
          region: "Люлин",
          mdtName: "ОТДЕЛ МДТ",
          graoName: "ОТДЕЛ ГРАО",
          mdtPhone1: "029041244  ",
          mdtPhone2: "029041245",
          mdtPhone3: "029041246",
          mdtPhone4: "029041247",
          mdtPhone5: "",
          graoPhone1: "029917230",
          graoPhone2: "",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "http://ovchakupel.bg/",
          region: "Овча купел",
          mdtName: "ОТДЕЛ МДТ",
          graoName: "ОТДЕЛ ГРАО",
          mdtPhone1: "029555833",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "029554462",
          graoPhone2: "0898778723",
          graoPhone3: "028556161",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "http://www.so-nadejda.com/",
          region: "Надежда",
          mdtName: "ОТДЕЛ МДТ Надежда и Връбница",
          graoName: "ОТДЕЛ ГРАО",
          mdtPhone1: "029041188",
          mdtPhone2: "029041191",
          mdtPhone3: "029041193",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "024951155",
          graoPhone2: "",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://mladost.bg/",
          region: "Младост",
          mdtName: "ОТДЕЛ МДТ Надежда и Връбница",
          graoName: "ОТДЕЛ ГРАО",
          mdtPhone1: "029743735",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "029067668",
          graoPhone2: "029067669",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://studentski.bg/",
          region: "Студентски",
          mdtName: "ОТДЕЛ МДТ",
          graoName: "ОТДЕЛ ГРАО",
          mdtPhone1: "029041221",
          mdtPhone2: "029041224",
          mdtPhone3: "029041225",
          mdtPhone4: "029041226",
          mdtPhone5: "",
          graoPhone1: "028683124",
          graoPhone2: "",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
      ],
    },
  },
  en: {
    [contactsPageBlogs.CONTACTS_BLOCK]: {
      items: [
        {
          link: "https://bankya.bg/",
          region: "Bankya",
          mdtName: "LTF",
          graoName: "CRAS",
          mdtPhone1: "029977045",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "029977261",
          graoPhone2: "029977029101",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://raionvitosha.eu/bg/",
          region: "Vitosha",
          mdtName: "LTF",
          graoName: "CRAS",
          mdtPhone1: "029555953",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "028187918",
          graoPhone2: "",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://raionvitosha.eu/bg/",
          region: "Vrabnitsa",
          mdtName: "LTF",
          graoName: "CRAS",
          mdtPhone1: "029041188",
          mdtPhone2: "029041191",
          mdtPhone3: "029041193",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "024957740",
          graoPhone2: "024957707",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://www.so-vazrajdane.bg/",
          region: "Vuzrajdane",
          mdtName: "LTF",
          graoName: "CRAS",
          mdtPhone1: "029041196",
          mdtPhone2: "029041197",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "029814364",
          graoPhone2: "",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://rayon-oborishte.bg/",
          region: "Oborishte",
          mdtName: "LTF",
          graoName: "CRAS",
          mdtPhone1: "029434835",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "029431840",
          graoPhone2: "",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://so-izgrev.bg/",
          region: "Izgrev",
          mdtName: "LTF",
          graoName: "CRAS",
          mdtPhone1: "029041220",
          mdtPhone2: "029041219",
          mdtPhone3: "029041218",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "029701025",
          graoPhone2: "",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://lozenets.sofia.bg/",
          region: "Lozenets",
          mdtName: "LTF",
          graoName: "CRAS",
          mdtPhone1: "029800912",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "070020555",
          graoPhone2: "",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "http://www.serdika.bg/",
          region: "Serdika",
          mdtName: "LTF",
          graoName: "CRAS",
          mdtPhone1: "029311478",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "028322095",
          graoPhone2: " 029218017",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://so-slatina.org/",
          region: "Slatina",
          mdtName: "LTF",
          graoName: "CRAS",
          mdtPhone1: "029311478",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "028709246",
          graoPhone2: " 028703218",
          graoPhone3: "028731482",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://sredec-sofia.org/",
          region: "Sredets",
          mdtName: "LTF Sredets and Triaditsa",
          graoName: "CRAS Sredets",
          mdtPhone1: "029809076",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "029484317",
          graoPhone2: "",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://triaditza.org/",
          region: "Triaditsa",
          mdtName: "LTF Sredets and Triaditsa",
          graoName: "CRAS Triaditsa",
          mdtPhone1: "029809076",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "028054117",
          graoPhone2: "028054119",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://www.krasnapoliana.com/",
          region: "Krasna polqna",
          mdtName: "LTF",
          graoName: "CRAS",
          mdtPhone1: "029201624",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "029217256",
          graoPhone2: "029217237",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://www.krasnoselo.net/",
          region: "Krasno selo",
          mdtName: "LTF",
          graoName: "CRAS",
          mdtPhone1: "029557325",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "028951142",
          graoPhone2: "",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "http://kremikovci.org/",
          region: "Kremikovci",
          mdtName: "LTF",
          graoName: "CRAS",
          mdtPhone1: "029945672",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "029945491",
          graoPhone2: "",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "http://www.pancharevo.org/",
          region: "Pancharevo",
          mdtName: "LTF",
          graoName: "CRAS",
          mdtPhone1: "029041234",
          mdtPhone2: "029041235",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "029760506",
          graoPhone2: "029923120",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://www.poduiane.info/",
          region: "Poduyane",
          mdtName: "LTF",
          graoName: "CRAS",
          mdtPhone1: "029455287",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "028146100",
          graoPhone2: "",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://www.ilinden.bg/",
          region: "Ilinden",
          mdtName: "LTF",
          graoName: "CRAS",
          mdtPhone1: "028211265",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "024397322",
          graoPhone2: "024397322",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://raioniskar.bg/",
          region: "Iskar",
          mdtName: "LTF",
          graoName: "CRAS",
          mdtPhone1: "029790572",
          mdtPhone2: "029790450",
          mdtPhone3: "029794897",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "029790740",
          graoPhone2: "",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "http://www.novi-iskar.bg/",
          region: "Novi Iskar",
          mdtName: "LTF",
          graoName: "CRAS",
          mdtPhone1: "029918381",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "029917230",
          graoPhone2: "",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://www.lyulin.bg/",
          region: "Liulin",
          mdtName: "LTF",
          graoName: "CRAS",
          mdtPhone1: "029041244  ",
          mdtPhone2: "029041245",
          mdtPhone3: "029041246",
          mdtPhone4: "029041247",
          mdtPhone5: "",
          graoPhone1: "029917230",
          graoPhone2: "",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "http://ovchakupel.bg/",
          region: "Ovcha Kupel",
          mdtName: "LTF",
          graoName: "CRAS",
          mdtPhone1: "029555833",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "029554462",
          graoPhone2: "0898778723",
          graoPhone3: "028556161",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "http://www.so-nadejda.com/",
          region: "Nadejda",
          mdtName: "LTF Nadejda and Vrabnitsa",
          graoName: "CRAS",
          mdtPhone1: "029041188",
          mdtPhone2: "029041191",
          mdtPhone3: "029041193",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "024951155",
          graoPhone2: "",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://mladost.bg/",
          region: "Mladost",
          mdtName: "LTF",
          graoName: "CRAS",
          mdtPhone1: "029743735",
          mdtPhone2: "",
          mdtPhone3: "",
          mdtPhone4: "",
          mdtPhone5: "",
          graoPhone1: "029067668",
          graoPhone2: "029067669",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
        {
          link: "https://studentski.bg/",
          region: "Studentski",
          mdtName: "LTF",
          graoName: "CRAS",
          mdtPhone1: "029041221",
          mdtPhone2: "029041224",
          mdtPhone3: "029041225",
          mdtPhone4: "029041226",
          mdtPhone5: "",
          graoPhone1: "028683124",
          graoPhone2: "",
          graoPhone3: "",
          graoPhone4: "",
          graoPhone5: "",
        },
      ],
    },
  },
};
