import { PAGE_NAMES, PAGE_BLOCKS } from "../../../constants/pages";

const cookiePolicyPageBlocks = PAGE_BLOCKS[PAGE_NAMES.COOKIE_POLICY];

export default {
  bg: {
    [cookiePolicyPageBlocks.COOKIE_POLICY_BLOCK]: {
      text: `<h1><strong>Бисквитки</strong></h1><p>&nbsp;</p><h3><strong>Какво представляват бисквитките?</strong></h3><p>Бисквитките са малки текстови файлове, които се запазват на вашия компютър или мобилно устройство, когато посещавате даден уебсайт. Те позволяват на уебсайта да запаметява вашите действия и предпочитания (като например потребителско име, език, размер на шрифта и други настройки за показване) за определен период от време, за да не се налага да ги въвеждате всеки път, когато посещавате сайта или преминавате от една страница към друга.</p><p><br></p><h3><strong>По какъв начин използваме бисквитките?</strong></h3><p>Бисквитките, които използваме, са такива запазващи информация за настройките на достъпност на сайта - размер на шрифта, цветова тема, форматиращи кода стилове. Бисквитките, които използваме за контрол на вида на сайта, са такива осигуряващи достъп на хора в неравностойно положение и важат докато не бъдат изключени от съответната опция. Също така използваме и сесийни бисквитки, за да не се налага да извършвате вход в потребителския си профил всеки път, когато смените текуща страница от сайта.</p><p><br></p><h3><strong>Как да контролирате бисквитките?</strong></h3><p>Можете да контролирате и/или изтривате бисквитки когато пожелаете – за повече информация вижте https://aboutcookies.org. Можете да изтриете всички бисквитки, които вече са запазени на вашия компютър, а също така можете да настроите повечето браузъри да ги блокират. Ако направите това обаче, може да се наложи ръчно да настройвате някои параметри всеки път, когато посещавате даден сайт, а освен това е възможно някои услуги и функции да не работят.</p><p><br></p><h3><strong>Google Analytics бисквитки</strong></h3><p>Сайтът използва услугата Analytics, събираща статистика за потреблението. За целта се използват бисквитки. За отказ от Google Analytics бисквитки, отворете <a href="https://tools.google.com/dlpage/gaoptout" rel="noopener noreferrer" target="_blank">този линк</a>.</p>`,
    },
  },
  en: {
    [cookiePolicyPageBlocks.COOKIE_POLICY_BLOCK]: {
      text: `<h1><strong>Cookie Policy</strong></h1><p>&nbsp;</p><h3><strong>What are cookies?</strong></h3><p>Cookies are small text files that are saved on your computer or mobile device when you visit a website. They allow the website to store your actions and preferences (such as username, language, font size, and other display settings) for a certain period of time so you do not have to enter them each time you visit the site or go from one page to another page.</p><p><br></p><h3><strong>How do we use the cookies?</strong></h3><p>The cookies we use store configuration information for accessibility of the site - font size, color theme, code formatting styles. The cookies we use to control the type of site provide access for disadvantaged people and are valid until they are disabled from the respective option. We also use session cookies so you do not have to sign in to your profile each time you change a current site page.</p><p><br></p><h3><strong>How to control cookies?</strong></h3><p>You can control and/or delete cookies whenever you want - for more information, see https://aboutcookies.org. You can delete all the cookies already saved on your computer, and you can also set most browsers to block them. However, if you do so, you may need to manually configure some parameters each time you visit a site, and some services and features may not work.</p><p><br></p><h3><strong>Google Analytics cookies</strong></h3><p>The portal <a href="https://www.sofia.bg/" rel="noopener noreferrer" target="_blank">https://www.sofia.bg</a> uses the Analytics service to collect traffic data in the websites that build the portal. Cookies are used for this purpose. To cancel Google Analytics cookies, please open <a href="https://tools.google.com/dlpage/gaoptout" rel="noopener noreferrer" target="_blank">this link</a>.</p>`,
    },
  },
};
